/* ============================================================
   CableSpec Pro — AWG Cable & Connector Sizing Data
   ============================================================ */

/* ── AWG Reference Data ── */
const AWG_DATA = [
  {
    awg: 28, mm2: 0.08, condOD: '0.36', currentA: '0.5A',
    resistance: '213.0', use: 'signal', useClass: 'use-signal', useLabel: 'Signal / Data',
    od: { PVC: '2.0–3.2', PUR: '2.2–3.4', TPE: '2.3–3.6', Silicone: '2.5–3.8' },
    connectors: ['M5', 'M8'],
    note: 'Fine-wire signal only. Encoder, proximity sensor short links.',
  },
  {
    awg: 26, mm2: 0.14, condOD: '0.46', currentA: '1.0A',
    resistance: '133.9', use: 'signal', useClass: 'use-signal', useLabel: 'Signal / Data',
    od: { PVC: '2.5–3.8', PUR: '2.6–4.0', TPE: '2.8–4.2', Silicone: '3.0–4.5' },
    connectors: ['M5', 'M8'],
    note: 'Low-current sensor, thermocouple extension, data bus wire.',
  },
  {
    awg: 24, mm2: 0.25, condOD: '0.51', currentA: '2.0A',
    resistance: '84.2',  use: 'signal', useClass: 'use-signal', useLabel: 'Signal / Data',
    od: { PVC: '3.0–5.0', PUR: '3.2–5.2', TPE: '3.5–5.5', Silicone: '3.8–5.8' },
    connectors: ['M5', 'M8', 'M12'],
    note: 'Standard sensor cable. Most common for M8/M12 NPN/PNP proximity sensors.',
  },
  {
    awg: 22, mm2: 0.34, condOD: '0.64', currentA: '3.0A',
    resistance: '53.5',  use: 'signal', useClass: 'use-signal', useLabel: 'Signal / Data',
    od: { PVC: '3.5–5.5', PUR: '3.8–6.0', TPE: '4.0–6.2', Silicone: '4.2–6.5' },
    connectors: ['M8', 'M12'],
    note: 'General control signal. 4-core PUR for M12 A-code automation sensors.',
  },
  {
    awg: 20, mm2: 0.50, condOD: '0.81', currentA: '5.0A',
    resistance: '33.6',  use: 'hybrid', useClass: 'use-hybrid', useLabel: 'Hybrid',
    od: { PVC: '4.0–6.5', PUR: '4.5–7.0', TPE: '4.8–7.2', Silicone: '5.0–7.5' },
    connectors: ['M12', 'M16'],
    note: 'Power + signal hybrid. 5-pin M12 valve/actuator cables, AS-Interface.',
  },
  {
    awg: 18, mm2: 1.00, condOD: '1.02', currentA: '10A',
    resistance: '21.3',  use: 'power', useClass: 'use-power', useLabel: 'Power',
    od: { PVC: '5.0–7.5', PUR: '5.5–8.0', TPE: '6.0–8.5', Silicone: '6.5–9.0' },
    connectors: ['M12', 'M16', 'M23'],
    note: 'Light power distribution. 24V DC actuator feeds. M12 power (A/S/T code).',
  },
  {
    awg: 16, mm2: 1.50, condOD: '1.29', currentA: '13A',
    resistance: '13.4',  use: 'power', useClass: 'use-power', useLabel: 'Power',
    od: { PVC: '6.0–9.0', PUR: '6.5–9.5', TPE: '7.0–10.0', Silicone: '7.5–10.5' },
    connectors: ['M16', 'M23'],
    note: 'Motor power, solenoid valve feeds. 230V / 400V low-current loads.',
  },
  {
    awg: 14, mm2: 2.50, condOD: '1.63', currentA: '20A',
    resistance: '8.4',   use: 'power', useClass: 'use-power', useLabel: 'Power',
    od: { PVC: '7.0–11.0', PUR: '7.5–11.5', TPE: '8.0–12.0', Silicone: '9.0–13.0' },
    connectors: ['M23', 'Han-Modular'],
    note: 'Medium power. Servo motor phase cable, 3-phase sub-panel feeds.',
  },
  {
    awg: 12, mm2: 4.00, condOD: '2.05', currentA: '25A',
    resistance: '5.3',   use: 'power', useClass: 'use-power', useLabel: 'Power',
    od: { PVC: '9.0–13.0', PUR: '9.5–13.5', TPE: '10.0–14.0', Silicone: '11.0–15.0' },
    connectors: ['M23', 'Han-Modular', 'CEE 16A'],
    note: 'Industrial power feeds. VFD output, pump motor, 3-phase 16A circuits.',
  },
  {
    awg: 10, mm2: 6.00, condOD: '2.59', currentA: '32A',
    resistance: '3.3',   use: 'power', useClass: 'use-power', useLabel: 'Power',
    od: { PVC: '11.0–15.0', PUR: '11.5–15.5', TPE: '12.0–16.0', Silicone: '13.0–17.0' },
    connectors: ['M23', 'Han-Modular', 'CEE 32A'],
    note: 'Heavy power cable. Main machine incomers, large servo drives.',
  },
  {
    awg: 8, mm2: 10.0, condOD: '3.26', currentA: '55A',
    resistance: '2.1',   use: 'power', useClass: 'use-power', useLabel: 'Power',
    od: { PVC: '13.0–17.0', PUR: '14.0–18.0', TPE: '14.5–18.5', Silicone: '15.0–19.0' },
    connectors: ['Han-Modular', 'CEE 63A'],
    note: 'High-current supply. Main distribution, 63A circuits, welding power.',
  },
  {
    awg: 6, mm2: 16.0, condOD: '4.11', currentA: '75A',
    resistance: '1.3',   use: 'power', useClass: 'use-power', useLabel: 'Power',
    od: { PVC: '16.0–21.0', PUR: '17.0–22.0', TPE: '17.5–22.5', Silicone: '18.0–23.0' },
    connectors: ['Han-Modular', 'CEE 63A'],
    note: 'High-power. EV charging cables (Type 2 AC), main feeder cables.',
  },
];

/* ── M-Series Connector Data ── */
const M_SERIES = [
  {
    series: 'M5',
    color: '#a78bfa',
    glow: 'rgba(167,139,250,0.4)',
    bgA: 'rgba(167,139,250,0.08)',
    bgB: 'rgba(167,139,250,0.02)',
    ipRating: 'IP67/IP68',
    threadDia: '5 mm',
    cableEntryMin: '2.0 mm',
    cableEntryMax: '4.5 mm',
    awgCompatible: [28, 26, 24],
    awgMarginal: [],
    tempRange: '-25°C to +70°C',
    standard: 'IEC 61076-2-110',
    matings: '≥ 5,000',
    keying: 'None (unkeyed)',
    description: 'Ultra-compact connector for miniaturized sensors. Used in tight machine spaces. Pin count limited to 3 pins only.',
    pins: [
      { count: 3, keying: 'Unkeyed', awgMatch: '28–24 AWG', gender: ['M','F'], application: 'NPN/PNP sensor (DC power + signal)', maxCurrent: '1A/pin' },
    ],
  },
  {
    series: 'M8',
    color: '#38bdf8',
    glow: 'rgba(56,189,248,0.4)',
    bgA: 'rgba(56,189,248,0.08)',
    bgB: 'rgba(56,189,248,0.02)',
    ipRating: 'IP67/IP68/IP69K',
    threadDia: '8 mm',
    cableEntryMin: '3.0 mm',
    cableEntryMax: '6.0 mm',
    awgCompatible: [28, 26, 24, 22],
    awgMarginal: [20],
    tempRange: '-25°C to +85°C',
    standard: 'IEC 61076-2-104',
    matings: '≥ 10,000',
    keying: 'A-Code (std), B-Code (DC power)',
    description: 'Compact sensor connector standard in automation. Supports 3 and 4 pin configurations. A-code for signals, B-code for high-power 4A.',
    pins: [
      { count: 3, keying: 'A-Code', awgMatch: '28–22 AWG', gender: ['M','F'], application: 'NPN/PNP sensor (3-wire)', maxCurrent: '4A/pin' },
      { count: 4, keying: 'A-Code', awgMatch: '28–22 AWG', gender: ['M','F'], application: 'Photoelectric / valve (4-wire)', maxCurrent: '4A/pin' },
      { count: 4, keying: 'B-Code', awgMatch: '26–22 AWG', gender: ['M','F'], application: 'High-power 24V DC actuator bus', maxCurrent: '8A/pin' },
    ],
  },
  {
    series: 'M12',
    color: '#34d399',
    glow: 'rgba(52,211,153,0.4)',
    bgA: 'rgba(52,211,153,0.08)',
    bgB: 'rgba(52,211,153,0.02)',
    ipRating: 'IP67/IP68/IP69K',
    threadDia: '12 mm',
    cableEntryMin: '4.0 mm',
    cableEntryMax: '8.0 mm',
    awgCompatible: [24, 22, 20, 18],
    awgMarginal: [26, 16],
    tempRange: '-40°C to +105°C (PUR) / +125°C (PTFE)',
    standard: 'IEC 61076-2-101',
    matings: '≥ 10,000',
    keying: 'A / B / C / D / X / T / S / K codes',
    description: 'The dominant industrial sensor/actuator connector globally. Multiple keying codes serve different protocols. Supports 3 to 12 pins depending on code.',
    pins: [
      { count: 3, keying: 'A-Code', awgMatch: '24–20 AWG', gender: ['M','F'], application: '3-wire sensor (DC+, 0V, signal)', maxCurrent: '4A/pin' },
      { count: 4, keying: 'A-Code', awgMatch: '24–20 AWG', gender: ['M','F'], application: '4-wire sensor, solenoid valve', maxCurrent: '4A/pin' },
      { count: 5, keying: 'A-Code', awgMatch: '24–20 AWG', gender: ['M','F'], application: '5-wire (AS-i, safety, valve pilot)', maxCurrent: '4A/pin' },
      { count: 4, keying: 'B-Code', awgMatch: '24–20 AWG', gender: ['M','F'], application: 'PROFIBUS DP (2-wire + shield)', maxCurrent: '4A/pin' },
      { count: 4, keying: 'D-Code', awgMatch: '24–22 AWG', gender: ['M','F'], application: '100BASE-TX Ethernet (EtherNet/IP, PROFINET)', maxCurrent: '1A/pin' },
      { count: 8, keying: 'X-Code', awgMatch: '26–24 AWG', gender: ['M','F'], application: 'Gigabit / 10GbE Ethernet (4 twisted pairs)', maxCurrent: '0.8A/pin' },
      { count: 5, keying: 'S-Code', awgMatch: '22–18 AWG', gender: ['M','F'], application: 'Power (AC/DC up to 630V, 12A)', maxCurrent: '12A/pin' },
      { count: 5, keying: 'T-Code', awgMatch: '22–18 AWG', gender: ['M','F'], application: 'Power DC 630V 16A actuator / motor', maxCurrent: '16A/pin' },
      { count: 12, keying: 'A-Code', awgMatch: '28–24 AWG', gender: ['M','F'], application: 'Multi-pin signal (I/O module, encoder)', maxCurrent: '2A/pin' },
      { count: 17, keying: 'A-Code', awgMatch: '28–26 AWG', gender: ['M','F'], application: 'High-density digital I/O bus', maxCurrent: '1A/pin' },
    ],
  },
  {
    series: 'M16',
    color: '#fbbf24',
    glow: 'rgba(251,191,36,0.4)',
    bgA: 'rgba(251,191,36,0.08)',
    bgB: 'rgba(251,191,36,0.02)',
    ipRating: 'IP67',
    threadDia: '16 mm',
    cableEntryMin: '6.0 mm',
    cableEntryMax: '10.0 mm',
    awgCompatible: [20, 18, 16],
    awgMarginal: [22, 14],
    tempRange: '-25°C to +85°C',
    standard: 'IEC 61076-2-106',
    matings: '≥ 5,000',
    keying: 'A-Code (std)',
    description: 'Mid-size connector bridging M12 and M23. Used for higher-current actuators and hybrid power+signal cable assemblies. Supports 4 to 17 pins.',
    pins: [
      { count: 4, keying: 'A-Code', awgMatch: '20–16 AWG', gender: ['M','F'], application: 'Motor / actuator 3-phase + PE', maxCurrent: '16A/pin' },
      { count: 5, keying: 'A-Code', awgMatch: '20–16 AWG', gender: ['M','F'], application: 'Power + PE + feedback signal', maxCurrent: '16A/pin' },
      { count: 8, keying: 'A-Code', awgMatch: '22–18 AWG', gender: ['M','F'], application: 'Encoder + power hybrid', maxCurrent: '8A/pin' },
      { count: 17, keying: 'A-Code', awgMatch: '24–22 AWG', gender: ['M','F'], application: 'Dense I/O backplane connector', maxCurrent: '4A/pin' },
    ],
  },
  {
    series: 'M23',
    color: '#fb923c',
    glow: 'rgba(251,146,60,0.4)',
    bgA: 'rgba(251,146,60,0.08)',
    bgB: 'rgba(251,146,60,0.02)',
    ipRating: 'IP67',
    threadDia: '23 mm',
    cableEntryMin: '8.0 mm',
    cableEntryMax: '14.0 mm',
    awgCompatible: [16, 14, 12],
    awgMarginal: [18, 10],
    tempRange: '-40°C to +105°C',
    standard: 'IEC 61076-2-115',
    matings: '≥ 5,000',
    keying: 'Standard / Servo (K-code)',
    description: 'Large industrial circular connector for heavy servo motors, hybrid power+data, and high-current machine tool applications. Most common in servo and spindle drive systems.',
    pins: [
      { count: 7, keying: 'Standard', awgMatch: '16–12 AWG', gender: ['M','F'], application: 'High-current power (up to 25A/pin)', maxCurrent: '25A/pin' },
      { count: 12, keying: 'Standard', awgMatch: '18–14 AWG', gender: ['M','F'], application: 'Servo motor: power + brake + thermal', maxCurrent: '16A/pin' },
      { count: 19, keying: 'Standard', awgMatch: '22–18 AWG', gender: ['M','F'], application: 'Servo + encoder hybrid (full hybrid)', maxCurrent: '10A/pin' },
    ],
  },
  {
    series: 'Han®',
    color: '#e879f9',
    glow: 'rgba(232,121,249,0.4)',
    bgA: 'rgba(232,121,249,0.08)',
    bgB: 'rgba(232,121,249,0.02)',
    ipRating: 'IP65/IP66/IP67',
    threadDia: '—',
    cableEntryMin: '6.0 mm',
    cableEntryMax: '25.0 mm',
    awgCompatible: [14, 12, 10, 8, 6],
    awgMarginal: [16, 4],
    tempRange: '-40°C to +125°C',
    standard: 'DIN VDE 0627 / IEC 61984',
    matings: '≥ 500 (heavy duty)',
    keying: 'Modular (interchangeable inserts)',
    description: 'Harting Han® modular rectangular industrial connector. Interchangeable power, signal, data, and fibre inserts in one housing. Used for machine interfaces, cabinet connections, and industrial panel connectors.',
    pins: [
      { count: '2–4', keying: 'Power insert', awgMatch: '14–6 AWG', gender: ['M','F'], application: 'High-current power (up to 200A)', maxCurrent: '200A/pin' },
      { count: '10–16', keying: 'Signal insert', awgMatch: '24–16 AWG', gender: ['M','F'], application: 'Control signal, I/O, fieldbus', maxCurrent: '10A/pin' },
      { count: '4–24', keying: 'Data insert (RJ45)', awgMatch: 'RJ45 format', gender: ['M','F'], application: 'Ethernet, PROFINET panel connection', maxCurrent: 'N/A' },
      { count: '2', keying: 'Fibre insert', awgMatch: 'LC/SC fibre', gender: ['M','F'], application: 'Fibre optic data link in panel', maxCurrent: 'N/A' },
    ],
  },
];

/* ── Sheath / Jacket Material Data ── */
const SHEATH_DATA = [
  {
    name: 'PVC',
    fullName: 'Polyvinyl Chloride',
    color: '#60a5fa',
    props: [
      { key: 'Temp Range',       val: '-15°C to +70°C' },
      { key: 'Flexibility',      val: 'Good (static)' },
      { key: 'Oil Resistance',   val: 'Moderate' },
      { key: 'UV Resistance',    val: 'Moderate (add stabiliser)' },
      { key: 'Chemical Resist',  val: 'Good (acids, alkalis)' },
      { key: 'Cost',             val: '★☆☆ (lowest)' },
      { key: 'Halogen-free',     val: '✗ No (chlorine)' },
      { key: 'Flame Rating',     val: 'UL VW-1 / IEC 60332-1' },
    ],
    awgRange: [28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6],
    connectors: ['M5', 'M8', 'M12', 'M16', 'M23', 'Han-Modular'],
    odAddSingle: '+1.8 to +2.5 mm over conductor OD (single-core)',
    notes: 'Best value for static applications indoors. Avoid in oil zones or drag-chain. Avoid in food/pharma (plasticisers). Widely used for M8/M12 pigtail cables.',
    uses: ['Control panels', 'Indoor sensors', 'Power distribution', 'Building wiring', 'Office/lab instruments'],
  },
  {
    name: 'PUR',
    fullName: 'Polyurethane',
    color: '#34d399',
    props: [
      { key: 'Temp Range',       val: '-40°C to +80°C' },
      { key: 'Flexibility',      val: 'Excellent (flex/drag-chain)' },
      { key: 'Oil Resistance',   val: 'Excellent (mineral oils)' },
      { key: 'UV Resistance',    val: 'Good' },
      { key: 'Chemical Resist',  val: 'Good (hydrolysis at >60°C)' },
      { key: 'Cost',             val: '★★☆ (medium)' },
      { key: 'Halogen-free',     val: '✓ Yes' },
      { key: 'Flame Rating',     val: 'IEC 60332-1 / UL 508' },
    ],
    awgRange: [28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8],
    connectors: ['M5', 'M8', 'M12', 'M16', 'M23', 'Han-Modular'],
    odAddSingle: '+2.0 to +2.8 mm over conductor OD (single-core)',
    notes: 'The default choice for robotics, drag chains, machine tools with coolant. Excellent abrasion and oil resistance. Most M12 factory automation cables use PUR.',
    uses: ['Robot drag-chain', 'CNC machine tools', 'Automated assembly', 'Automotive welding cells', 'Food-adjacent (washdown sides)'],
  },
  {
    name: 'TPE',
    fullName: 'Thermoplastic Elastomer',
    color: '#f472b6',
    props: [
      { key: 'Temp Range',       val: '-50°C to +90°C' },
      { key: 'Flexibility',      val: 'Excellent (cold flex)' },
      { key: 'Oil Resistance',   val: 'Good' },
      { key: 'UV Resistance',    val: 'Very Good (outdoor rated)' },
      { key: 'Chemical Resist',  val: 'Good (varied by grade)' },
      { key: 'Cost',             val: '★★☆ (medium)' },
      { key: 'Halogen-free',     val: '✓ Yes (LSZH grades)' },
      { key: 'Flame Rating',     val: 'IEC 60332-3 / EN 45545' },
    ],
    awgRange: [28, 26, 24, 22, 20, 18, 16, 14, 12, 10],
    connectors: ['M8', 'M12', 'M16', 'M23'],
    odAddSingle: '+2.2 to +3.0 mm over conductor OD (single-core)',
    notes: 'Excellent cold-flexibility makes it ideal for outdoor and Arctic applications. Preferred for railway (EN 45545 HL3) and outdoor agriculture. LSZH grades for tunnels/rail.',
    uses: ['Railway rolling stock', 'Outdoor agriculture', 'Arctic mining', 'Wind turbine towers', 'Marine topside'],
  },
  {
    name: 'Silicone',
    fullName: 'Silicone Rubber',
    color: '#fb923c',
    props: [
      { key: 'Temp Range',       val: '-60°C to +180°C' },
      { key: 'Flexibility',      val: 'Outstanding (remains soft)' },
      { key: 'Oil Resistance',   val: 'Poor (avoid petroleum oil)' },
      { key: 'UV Resistance',    val: 'Excellent' },
      { key: 'Chemical Resist',  val: 'Excellent (acids, bases)' },
      { key: 'Cost',             val: '★★★ (highest)' },
      { key: 'Halogen-free',     val: '✓ Yes' },
      { key: 'Flame Rating',     val: 'Self-extinguishing / UL94 HB' },
    ],
    awgRange: [28, 26, 24, 22, 20, 18, 16],
    connectors: ['M8', 'M12'],
    odAddSingle: '+2.5 to +3.5 mm over conductor OD (single-core)',
    notes: 'Specified when extreme temperature resistance is critical. Medical, foundry, steam, baking ovens. Cannot be used near petroleum oils. Larger OD than PVC/PUR.',
    uses: ['Medical / patient leads', 'Furnaces & ovens', 'Steam autoclaves', 'Engine test cells', 'Lighting in hot zones'],
  },
  {
    name: 'PTFE/FEP',
    fullName: 'Polytetrafluoroethylene / Fluorinated Ethylene Propylene',
    color: '#a78bfa',
    props: [
      { key: 'Temp Range',       val: '-70°C to +260°C' },
      { key: 'Flexibility',      val: 'Limited (semi-rigid)' },
      { key: 'Oil Resistance',   val: 'Excellent (all chemicals)' },
      { key: 'UV Resistance',    val: 'Outstanding' },
      { key: 'Chemical Resist',  val: 'Outstanding (all solvents)' },
      { key: 'Cost',             val: '★★★ (premium)' },
      { key: 'Halogen-free',     val: '✗ No (fluorine-based)' },
      { key: 'Flame Rating',     val: 'Non-flammable (PTFE)' },
    ],
    awgRange: [28, 26, 24, 22, 20],
    connectors: ['M12', 'Specialty'],
    odAddSingle: '+0.4 to +1.0 mm over conductor OD (thin wall)',
    notes: 'Cleanroom, semiconductor, pharma, and military wire. Lowest outgassing. Thin-wall construction allows same OD as much thicker cables. NASA/MIL-W-22759 spec.',
    uses: ['Semiconductor fabs', 'Pharmaceutical reactors', 'Aerospace / MIL-spec', 'Downhole oil tools', 'RF microwave coax'],
  },
  {
    name: 'LSZH/LSOH',
    fullName: 'Low Smoke Zero Halogen',
    color: '#2dd4bf',
    props: [
      { key: 'Temp Range',       val: '-15°C to +70°C' },
      { key: 'Flexibility',      val: 'Good' },
      { key: 'Oil Resistance',   val: 'Moderate' },
      { key: 'UV Resistance',    val: 'Moderate' },
      { key: 'Chemical Resist',  val: 'Moderate' },
      { key: 'Cost',             val: '★★☆ (medium)' },
      { key: 'Halogen-free',     val: '✓ Yes (primary benefit)' },
      { key: 'Flame Rating',     val: 'IEC 60332-3 Cat C / EN 45545' },
    ],
    awgRange: [24, 22, 20, 18, 16, 14, 12],
    connectors: ['M12', 'M16', 'M23', 'Han-Modular'],
    odAddSingle: '+2.0 to +3.0 mm over conductor OD (single-core)',
    notes: 'Mandated in tunnels, underground railways, public buildings. Produces minimal smoke and no halogen acid gas when burning. EN 50264 for rail vehicles. IEC 60332-3 for buildings.',
    uses: ['Underground rail & metro', 'Road tunnels', 'Building risers', 'Offshore HVAC', 'Data center structured cabling'],
  },
];

/* ── AWG × Connector compatibility matrix ── */
// For each M-series, define AWG ranges per sheath type
const AWG_CONNECTOR_COMPAT = {
  M5:          { ok: [28,26,24],       marginal: [22],       max_od: 4.5  },
  M8:          { ok: [28,26,24,22],    marginal: [20],       max_od: 6.0  },
  M12:         { ok: [26,24,22,20,18], marginal: [16,28],    max_od: 8.0  },
  M16:         { ok: [22,20,18,16],    marginal: [24,14],    max_od: 10.0 },
  M23:         { ok: [18,16,14,12],    marginal: [20,10],    max_od: 14.0 },
  'Han-Modular': { ok: [14,12,10,8,6], marginal: [16,4],    max_od: 25.0 },
};
