/* ============================================================
   CableSpec Pro — Industry Data (30+ sectors)
   ============================================================ */

const INDUSTRIES = {

  industrial: [

    {
      id: 'factory-automation',
      name: 'Factory Automation & Robotics',
      icon: '🤖',
      sector: 'Industrial & Manufacturing',
      filter: 'industrial',
      accentColor: '#f97316',
      colorA: 'rgba(249,115,22,0.08)',
      colorB: 'rgba(249,115,22,0.02)',
      cables: ['M12 4-pin', 'M8 3-pin', 'M5 Nano', 'Cat6A FTP', 'PROFIBUS', 'DeviceNet'],
      specs: ['IP67', 'IP68', 'EMC Shielded'],
      connectorCount: 18,
      description: 'Factory automation and robotics rely on a dense network of sensors, actuators, servo drives, vision systems, and safety components. These environments demand rugged, compact circular connectors capable of surviving continuous machine cycles, coolant exposure, vibration, and EMI from variable frequency drives. All connectors must withstand repeated mating cycles (>10,000) and maintain IP67 or IP68 sealing.',
      connectors: [
        { name: 'M12 A-Code 4-pin', application: 'Sensors, actuators, PLC I/O', ipRating: 'IP67/68', standard: 'IEC 61076-2-101' },
        { name: 'M12 D-Code 4-pin', application: '100BASE-TX Ethernet (EtherNet/IP, PROFINET)', ipRating: 'IP67', standard: 'IEC 61076-2-101' },
        { name: 'M12 X-Code 8-pin', application: 'Gigabit Ethernet, 10GbE industrial', ipRating: 'IP67', standard: 'IEC 61076-2-109' },
        { name: 'M8 3/4-pin', application: 'Compact sensors, cameras', ipRating: 'IP67', standard: 'IEC 61076-2-104' },
        { name: 'M5 Nano (3-pin)', application: 'Miniature sensors', ipRating: 'IP67', standard: 'IEC 61076-2-110' },
        { name: 'HAN-Modular (Han®)', application: 'Machine interface panels, power/signal hybrid', ipRating: 'IP65/66', standard: 'DIN VDE 0627' },
        { name: 'PROFIBUS 9-pin D-sub', application: 'PROFIBUS DP fieldbus backbone', ipRating: 'IP20', standard: 'IEC 61158' },
        { name: 'DeviceNet (Micro/Mini)', application: 'CAN-based device network', ipRating: 'IP67', standard: 'IEC 62026-3' },
      ],
      cables_detail: [
        'PROFIBUS cable (violet, 24 AWG twisted pair)',
        'PUR-jacketed servo cable with braided shield',
        'Cat6A S/FTP Industrial Ethernet cable',
        'Drag-chain rated (10M+ bend cycles)',
        'Oil & coolant resistant PUR/PVC hybrid jacket',
      ],
      standards: ['IEC 61076', 'PROFINET', 'EtherCAT', 'CC-Link IE', 'IO-Link'],
      useCases: [
        'Conveyor belt sensor arrays',
        'Collaborative robot (cobot) wrist connections',
        'Vision system cameras and lighting controllers',
        'Safety light curtain wiring',
        'Servo drive and encoder feedback cables',
      ],
    },

    {
      id: 'heavy-industry',
      name: 'Heavy Industry & Mining',
      icon: '⛏️',
      sector: 'Industrial & Manufacturing',
      filter: 'industrial',
      accentColor: '#78716c',
      colorA: 'rgba(120,113,108,0.08)',
      colorB: 'transparent',
      cables: ['SY Control', 'XLPE HV', 'Mining Trailing', 'Armoured SWA', 'M23'],
      specs: ['IP68', 'EX/ATEX', 'Flame Retardant'],
      connectorCount: 12,
      description: 'Mining, steel mills, quarrying, and heavy construction machinery operate in extreme environments with shock loads, abrasion, chemical exposure, and explosive atmospheres. Cables must meet flame-retardancy (FR), low smoke zero halogen (LSZH), and ATEX Zone 1/2 standards. Trailing cables on mobile machinery must be highly flexible and mechanically robust.',
      connectors: [
        { name: 'M23 19-pin', application: 'High-current industrial power and signal hybrid', ipRating: 'IP67', standard: 'IEC 61076-2-115' },
        { name: 'CEE Industrial Plug', application: 'Shore power, mobile equipment power supply (16-125A)', ipRating: 'IP44/67', standard: 'IEC 60309' },
        { name: 'ATEX Ex-e Plug/Socket', application: 'Hazardous area power connection, Zone 1', ipRating: 'IP66', standard: 'IEC 60079-7' },
        { name: 'Hubbell HBL Series', application: 'Heavy equipment power in USA mining', ipRating: 'IP44', standard: 'NEMA 4' },
        { name: 'M25/M40 Cable Glands', application: 'ATEX-rated cable entry points', ipRating: 'IP68', standard: 'IEC 60079-0' },
      ],
      cables_detail: [
        'Mining trailing cable (rubber, multi-core, 1-35kV)',
        'Steel Wire Armoured (SWA) power cable',
        'XLPE insulated medium-voltage cable (6.6kV–33kV)',
        'LSZH control cable for underground use',
        'Flame retardant EPR/PCP jacketed flexible',
      ],
      standards: ['ATEX Directive 2014/34/EU', 'IEC 60079', 'IECEx', 'IEC 60309', 'BS 6708'],
      useCases: [
        'Underground mine trailing cables for continuous miners',
        'Steel plant ladle crane power and control',
        'Quarry blast ignition systems',
        'Conveyor motor starters in dusty zones',
        'Explosive atmosphere instrumentation',
      ],
    },

    {
      id: 'food-beverage',
      name: 'Food & Beverage Processing',
      icon: '🍔',
      sector: 'Industrial & Manufacturing',
      filter: 'industrial',
      accentColor: '#84cc16',
      colorA: 'rgba(132,204,22,0.08)',
      colorB: 'transparent',
      cables: ['M12 Hygienic', 'M8 Wash-down', 'PTFE Cable', 'V1/V3 Valve', 'Cat6A FTP'],
      specs: ['IP69K', 'FDA', 'Stainless'],
      connectorCount: 10,
      description: 'Food processing plants undergo aggressive high-pressure washdowns with hot water, steam, caustic cleaning agents, and disinfectants. Connectors must achieve IP69K (15 cm, 80 bar, 80 °C, 360° spray) and be constructed from FDA-compliant stainless steel (316L) and non-toxic sealing materials. ECOLAB and 3-A Sanitary Standards compliance is often required.',
      connectors: [
        { name: 'M12 Hygienic (IP69K)', application: 'Sensors in wash-down zones, hygienic area', ipRating: 'IP69K', standard: 'IEC 61076-2-101' },
        { name: 'M8 Hygienic', application: 'Compact sensors on filling machines', ipRating: 'IP69K', standard: 'IEC 61076-2-104' },
        { name: 'V1 Valve Connector', application: 'Solenoid valves (Form A flat face)', ipRating: 'IP65', standard: 'EN 175301-803' },
        { name: 'V3 Valve Connector', application: 'Solenoid valves (Round M12 face)', ipRating: 'IP67', standard: 'EN 175301-803' },
        { name: 'Hygienic M12 316L SS', application: 'Crevice-free sensor connections', ipRating: 'IP69K', standard: 'ECOLAB / 3-A' },
      ],
      cables_detail: [
        'PUR drag-chain cable with high flex rating',
        'FDA-grade PTFE insulated cable',
        'Stainless steel braided shielded cable',
        'Silicone-jacketed cable (steam zone)',
        'LSZH food-safe multi-core control cable',
      ],
      standards: ['IP69K', '3-A Sanitary Standard', 'FDA 21 CFR', 'ECOLAB', 'IEC 61076'],
      useCases: [
        'Bottling line conveyor sensors',
        'CIP (Clean-in-Place) system valve control',
        'Pasteurizer temperature sensor wiring',
        'Slaughterhouse hose station connections',
        'Packaging machine vision and lighting',
      ],
    },

    {
      id: 'pharma',
      name: 'Pharmaceuticals & Chemical Processing',
      icon: '💊',
      sector: 'Industrial & Manufacturing',
      filter: 'industrial',
      accentColor: '#06b6d4',
      colorA: 'rgba(6,182,212,0.08)',
      colorB: 'transparent',
      cables: ['PTFE Coax', 'M12 IP69K', 'Pigtail Grade', 'SIL-rated', 'FEP Insulated'],
      specs: ['SIL 2/3', 'ATEX', 'FDA'],
      connectorCount: 9,
      description: 'Pharmaceutical cleanrooms and chemical plants require chemically inert connectors. Cables must resist corrosive solvents, acids, and pharmaceutical-grade cleaning agents. SIL (Safety Integrity Level) requirements may apply for process safety applications. Chemical plants often classify hazardous zones requiring ATEX-rated components.',
      connectors: [
        { name: 'M12 PEEK Body', application: 'Chemically resistant sensor connections', ipRating: 'IP68', standard: 'IEC 61076-2-101' },
        { name: 'ATEX M12 (Zone 1)', application: 'Hazardous chemical zone sensors', ipRating: 'IP67', standard: 'IEC 60079' },
        { name: 'Tri-Clamp Electrical Probe', application: 'Inline pH/conductivity sensors', ipRating: 'IP68', standard: '3-A / ASME-BPE' },
        { name: 'Han-Eco® A', application: 'Panel connectors in pharma cabinets', ipRating: 'IP65', standard: 'DIN VDE 0627' },
      ],
      cables_detail: [
        'PTFE/FEP insulated instrument cable',
        'SS-overbraid chemical resist. cable',
        'Chemically resistant polyamide-jacketed',
        'Fiber optic (immune to chemical EMI)',
        'SIL-certified safety I/O cable',
      ],
      standards: ['ATEX', 'IECEx', 'FDA 21 CFR', 'ASME-BPE', 'SIL IEC 61508'],
      useCases: [
        'Reactor pressure and temperature monitoring',
        'Cleanroom HVAC sensor wiring',
        'Solvent-proof valve actuator connections',
        'Bioreactor dissolved oxygen probes',
        'Safety instrumented system (SIS) loops',
      ],
    },

    {
      id: 'logistics-warehouse',
      name: 'Logistics, Warehousing & Packaging',
      icon: '📦',
      sector: 'Industrial & Manufacturing',
      filter: 'industrial',
      accentColor: '#f59e0b',
      colorA: 'rgba(245,158,11,0.08)',
      colorB: 'transparent',
      cables: ['M12 5-pin', 'Cat5e FTP', 'AS-Interface', 'Barcode Scanner', 'M8 4-pin'],
      specs: ['IP65', 'Drag Chain', 'EMI Shielded'],
      connectorCount: 11,
      description: 'Modern warehouses use extensive conveyor systems, AGVs (Automated Guided Vehicles), RFID readers, barcode scanners, and high-speed sorters. Cables run through cable trays and drag chains, requiring high-flex PUR jackets. AS-Interface simplifies sensor/actuator wiring with a single two-wire bus.',
      connectors: [
        { name: 'M12 5-pin A-Code', application: 'AS-Interface nodes, sensor bus', ipRating: 'IP67', standard: 'IEC 62026-2' },
        { name: 'M12 4-pin D-Code', application: 'PROFINET conveyor control', ipRating: 'IP67', standard: 'IEC 61076' },
        { name: 'M8 4-pin', application: 'Proximity sensors on sorter lanes', ipRating: 'IP65', standard: 'IEC 61076-2-104' },
        { name: 'USB 3.0 Type-B Industrial', application: 'Barcode scanner, label printer', ipRating: 'IP20', standard: 'USB IF' },
        { name: 'Rectangular D-Sub (DB9)', application: 'Warehouse management terminal serial ports', ipRating: 'IP20', standard: 'EIA-574' },
      ],
      cables_detail: [
        'AS-Interface flat cable (2-wire, yellow)',
        'Cat5e S/FTP Ethernet for WMS network',
        'PUR drag-chain rated flex cable',
        'AGV battery tray cable',
        'RFID coax cable (LMR-195)',
      ],
      standards: ['AS-Interface', 'PROFINET', 'EtherNet/IP', 'IEC 62026-2'],
      useCases: [
        'Sortation conveyor photoelectric sensors',
        'AGV navigation laser wiring',
        'Pallet stretch-wrap machine control',
        'Pick-to-light and put-to-light systems',
        'Cold storage warehouse sensor arrays',
      ],
    },

    {
      id: 'machine-building',
      name: 'Machine Building & OEMs',
      icon: '⚙️',
      sector: 'Industrial & Manufacturing',
      filter: 'industrial',
      accentColor: '#94a3b8',
      colorA: 'rgba(148,163,184,0.07)',
      colorB: 'transparent',
      cables: ['M12 Multi', 'Power M23', 'Cat6A Ind.', 'EtherCAT', 'Servo Encoder'],
      specs: ['IP67', 'CE Mark', 'RoHS'],
      connectorCount: 14,
      description: 'Machine builders (OEMs) design and ship complete production machines globally and must select connectors meeting international standards across multiple regions. Machines must comply with CE (EU), UL (USA), and CSA (Canada) marks. Flexibility in global socket standards is critical.',
      connectors: [
        { name: 'M12 A/B/D/X-Code', application: 'Full I/O, Ethernet, AS-i hybrid', ipRating: 'IP67/68', standard: 'IEC 61076' },
        { name: 'M23 (19-pin)', application: 'Servo motor power + feedback hybrid', ipRating: 'IP67', standard: 'IEC 61076-2-115' },
        { name: 'RJ45 Industrial (Cat6A)', application: 'EtherCAT, PROFINET, EtherNet/IP', ipRating: 'IP20/67', standard: 'IEEE 802.3' },
        { name: 'MINI Combicon (Phoenix)', application: 'Control cabinet terminal block I/O', ipRating: 'IP20', standard: 'IEC 60603-13' },
        { name: 'MCV 1.5 Plug', application: 'PCB-mounted signal interface', ipRating: 'IP20', standard: 'IEC 60603' },
      ],
      cables_detail: [
        'CE-certified PVC multi-core control cable',
        'UL-listed AWM style cable',
        'Oil-resistant TPE servo cable',
        'EtherCAT certified twisted pair cable',
        'Hybrid power + data cable (servo systems)',
      ],
      standards: ['CE Machinery Directive', 'UL 508A', 'CSA C22.2', 'RoHS 2', 'REACH'],
      useCases: [
        'CNC machining center wiring harness',
        'Injection molding machine axis control',
        'Welding robot cell connectivity',
        'Press brake servo drive connections',
        'OEM machine export CE/UL compliance',
      ],
    },

    {
      id: 'semiconductor',
      name: 'Semiconductor Manufacturing',
      icon: '🔬',
      sector: 'Industrial & Manufacturing',
      filter: 'industrial',
      accentColor: '#818cf8',
      colorA: 'rgba(129,140,248,0.08)',
      colorB: 'transparent',
      cables: ['PTFE Coax', 'SMA RF', 'Ultra-Clean', 'Grounded Shield', 'Fiber Optic'],
      specs: ['Cleanroom Class 1', 'ESD Safe', 'Low Outgassing'],
      connectorCount: 8,
      description: 'Semiconductor fabs (wafer manufacturing, lithography, deposition, etch) require cleanroom-compatible (Class 1-100) cables with near-zero outgassing. ESD-sensitive devices demand ESD-safe connectors with controlled impedance. RF connectors support plasma process generators operating at 13.56 MHz and 2.45 GHz.',
      connectors: [
        { name: 'SMA (SubMiniature-A)', application: 'RF plasma generator signal (50Ω)', ipRating: 'IP20', standard: 'MIL-STD-348' },
        { name: 'N-Type Coax', application: '2.45 GHz microwave plasma connection', ipRating: 'IP67', standard: 'IEC 61169-16' },
        { name: 'Ultra-Low Outgas Crimp', application: 'High-vacuum chamber wiring', ipRating: 'N/A', standard: 'NASA MSFC-SPEC-3425' },
        { name: 'Micro-D (MDM)', application: 'Compact equipment interconnect in cleanroom', ipRating: 'IP50', standard: 'MIL-DTL-83513' },
        { name: 'LEMO Series B', application: 'Instrument-to-chuck precision signal', ipRating: 'IP50', standard: 'LEMO B-Series' },
      ],
      cables_detail: [
        'PTFE cleanroom-grade coax (NASA spec)',
        'Low outgassing fiber optic cable',
        'Electroless nickel plated tinsel conductor',
        'PEEK insulated ultra-clean wire',
        'Anti-static braided shield cable',
      ],
      standards: ['NASA MSFC-SPEC-3425', 'SEMI F47', 'ASTM E595 (outgassing)', 'ANSI/ESD S20.20'],
      useCases: [
        'Lithography machine vibration sensor',
        'ALD/CVD chamber RF matching network',
        'Wafer chuck electrostatic connections',
        'Clean room AMHS robot interface',
        'Ion implanter beam control',
      ],
    },

  ],

  transport: [

    {
      id: 'automotive-mfg',
      name: 'Automotive Manufacturing',
      icon: '🏎️',
      sector: 'Transportation & Automotive',
      filter: 'transport',
      accentColor: '#3b82f6',
      colorA: 'rgba(59,130,246,0.08)',
      colorB: 'transparent',
      cables: ['FAKRA Z', 'HSD 4+2', 'HV Orange', 'LVDS', 'CAN Bus Twisted'],
      specs: ['AEC-Q100', 'LV214', 'USCAR-2'],
      connectorCount: 22,
      description: 'Modern vehicles contain 100+ ECUs connected by increasingly complex wiring harnesses. ADAS systems require high-speed LVDS and coaxial links for cameras and radar. EV powertrains add high-voltage (HV) orange-coded cables rated for 400–800V DC. Connectors must survive -40°C to +125°C and thousands of vibration hours per USCAR-2.',
      connectors: [
        { name: 'FAKRA SMB/Z-code', application: 'GPS, cellular antenna, ADAS camera', ipRating: 'IP50', standard: 'ISO 20860' },
        { name: 'HSD (High-Speed Data) 4+2', application: 'LVDS infotainment, MOST150 ring', ipRating: 'IP52', standard: 'Rosenberger HSD' },
        { name: 'HV Connector (HSK-HE)', application: 'EV battery pack, inverter, motor', ipRating: 'IP67', standard: 'ISO 6469-3' },
        { name: 'OBD-II (SAE J1962)', application: 'Diagnostics port (CAN/ISO 9141)', ipRating: 'IP20', standard: 'SAE J1962' },
        { name: 'MQS/MCON (TE/MX150)', application: 'ECU wire-to-board signal', ipRating: 'IP54', standard: 'USCAR-2' },
        { name: 'Deutsch DT/DTP Series', application: 'Engine, transmission control connectors', ipRating: 'IP67', standard: 'USCAR-2' },
        { name: 'Amphenol Mini-UHF', application: 'Vehicle antenna (AM/FM/DAB)', ipRating: 'IP40', standard: 'DIN 41585' },
      ],
      cables_detail: [
        'Thinwall CAN bus 2×0.35mm twisted pair',
        'LVDS coax 100Ω differential pair cable',
        'HV orange 70mm² shielded EV cable',
        'FlexRay dual-channel 100Ω cable',
        '1000BASE-T1 automotive Ethernet (single UTP)',
      ],
      standards: ['ISO 6722', 'USCAR-2', 'LV214', 'AEC-Q100', 'ISO 26262 ASIL'],
      useCases: [
        'EV battery management system wiring',
        'Surround-view camera harness (LVDS)',
        'ADAS radar front-end coax',
        'Body control module (BCM) multiplex',
        'Charging inlet (IEC 62196 Type 2)',
      ],
    },

    {
      id: 'commercial-vehicles',
      name: 'Commercial Vehicles & Trucking',
      icon: '🚛',
      sector: 'Transportation & Automotive',
      filter: 'transport',
      accentColor: '#f59e0b',
      colorA: 'rgba(245,158,11,0.07)',
      colorB: 'transparent',
      cables: ['SAE J560 7-pin', 'ISO 7638', 'Deutsch DTM', 'ABS Sensor', 'J1939 CAN'],
      specs: ['SAE J1939', 'IP67', 'Vibration'],
      connectorCount: 14,
      description: 'Heavy trucks, trailers, and buses use standardized tractor-trailer connectors for lighting and ABS. The CAN-based SAE J1939 protocol connects all powertrain and chassis ECUs. Connectors must survive road vibration, pressure washing, and -40°C Arctic operation.',
      connectors: [
        { name: 'SAE J560 7-way', application: 'Tractor-trailer lighting, ABS, power', ipRating: 'IP65', standard: 'SAE J560' },
        { name: 'ISO 7638 7-pin', application: 'EBS/ABS brake signal (Europe)', ipRating: 'IP67', standard: 'ISO 7638' },
        { name: 'Deutsch DT 2/4/6-pin', application: 'Engine, chassis control harness', ipRating: 'IP67', standard: 'USCAR-2' },
        { name: 'J1939 9-pin Deutsch (DRP9)', application: 'Diagnostic port (J1939 CAN)', ipRating: 'IP40', standard: 'SAE J1939' },
        { name: 'Superseal 1.5 (TE)', application: 'Exterior lighting, sealed I/O', ipRating: 'IP67', standard: 'USCAR-2' },
      ],
      cables_detail: [
        'J1939 CAN bus 2×0.5mm shielded',
        'SAE J1128 primary wire (GXL/SXL)',
        'SAE J378 battery cable 1/0-4/0 AWG',
        'ABS sensor screened 2-core cable',
        'Trailer umbilical cable 7-core',
      ],
      standards: ['SAE J1939', 'SAE J560', 'ISO 7638', 'ECE R13', 'FMVSS 121'],
      useCases: [
        'Fifth-wheel trailer lighting connection',
        'Engine management CAN harness',
        'Hydraulic tailgate solenoid control',
        'Tire pressure monitoring wiring',
        'Telematics fleet tracking antenna',
      ],
    },

    {
      id: 'railway',
      name: 'Railway & Mass Transit',
      icon: '🚆',
      sector: 'Transportation & Automotive',
      filter: 'transport',
      accentColor: '#e11d48',
      colorA: 'rgba(225,29,72,0.07)',
      colorB: 'transparent',
      cables: ['EN 50264 LSZH', 'WTB MVB', 'Radiax Leaky Coax', 'M23 Rail', 'Fiber Rail'],
      specs: ['EN 50155', 'HL3 Fire', 'Vibration Class'],
      connectorCount: 16,
      description: 'Rail vehicles require fire-retardant LSZH cables (EN 45545) that produce minimal smoke and toxic gas in tunnel fires. Electronic systems must meet EN 50155 for vibration, shock, humidity, and temperature. Train communication uses MVB (Multifunction Vehicle Bus) and WTB (Wire Train Bus) via UIC 556.',
      connectors: [
        { name: 'COTS M12/RJ45 Rail IP67', application: 'TCMS Ethernet (MVB over IP)', ipRating: 'IP67', standard: 'EN 50155' },
        { name: 'EN 50264 Crimp Terminal', application: 'LSZH rail cable termination', ipRating: 'IP20', standard: 'EN 50264' },
        { name: 'D-Sub 9-pin (RS-485)', application: 'WTB coupler in locomotive', ipRating: 'IP20', standard: 'UIC 556' },
        { name: 'SBB-type Draw Connector', application: 'Inter-vehicle UIC couplers', ipRating: 'IP54', standard: 'UIC 568' },
        { name: 'LEMO FHG Series', application: 'Passenger info, CCTV systems', ipRating: 'IP50', standard: 'EN 50155' },
        { name: 'Molex Mini-Fit Jr.', application: 'Passenger seat power outlets', ipRating: 'IP20', standard: 'UL 1977' },
      ],
      cables_detail: [
        'EN 50264 LSZH signalling cable (1.5–6mm²)',
        'EN 45545 HL3 flexible power cable',
        'WTB/MVB twisted pair (120Ω)',
        'Leaky (radiating) coax for tunnel GSM-R',
        'Armoured fibre optic for ETCS/ATP',
      ],
      standards: ['EN 50155', 'EN 45545', 'EN 50264', 'UIC 556', 'UIC 568', 'ETCS'],
      useCases: [
        'Train Control and Management System (TCMS)',
        'Passenger information display wiring',
        'CCTV surveillance in metro cars',
        'Traction motor power cable (1.5–25kV)',
        'GSM-R trackside radio antennas',
      ],
    },

    {
      id: 'aerospace-defense',
      name: 'Aerospace, Aviation & Defense',
      icon: '✈️',
      sector: 'Transportation & Automotive',
      filter: 'transport',
      accentColor: '#64748b',
      colorA: 'rgba(100,116,139,0.08)',
      colorB: 'transparent',
      cables: ['MIL-DTL-38999', 'ARINC 600', 'MIL-C-5015', 'AFDX', 'MIL-W-22759'],
      specs: ['MIL-SPEC', 'DO-160G', 'RTCA/DO-260'],
      connectorCount: 24,
      description: 'Aerospace and defense demand the most stringent connector specifications: hermetically sealed, shock/vibration rated per MIL-STD-810, and EMI screened. MIL-DTL-38999 Series III is the most common aerospace circular connector. Avionics buses include ARINC 429 (unidirectional), ARINC 664/AFDX (Ethernet), and MIL-STD-1553B. Fire survivability per AS23053 is critical.',
      connectors: [
        { name: 'MIL-DTL-38999 Ser. III', application: 'Primary avionics, flight control, EW systems', ipRating: 'IP67 (hermetic)', standard: 'MIL-DTL-38999' },
        { name: 'MIL-DTL-26482 Ser. II', application: 'Bayonet-lock avionics (legacy aircraft)', ipRating: 'IP67', standard: 'MIL-DTL-26482' },
        { name: 'ARINC 600 Rack Connector', application: 'Avionic Line Replaceable Unit (LRU)', ipRating: 'IP20', standard: 'ARINC 600' },
        { name: 'ARINC 404A Card', application: '400Hz avionics rack power', ipRating: 'IP20', standard: 'ARINC 404A' },
        { name: 'D38999/26 Quadrax', application: 'AFDX/ARINC 664 differential pairs', ipRating: 'IP67', standard: 'AS27837' },
        { name: 'SMA/SSMA RF Mil', application: 'Radar, EW antenna, GPS', ipRating: 'IP50', standard: 'MIL-STD-348' },
        { name: 'Thermocouple Connector (MS)', application: 'Engine EGT, turbine temperature', ipRating: 'IP20', standard: 'ANSI MC96.1' },
      ],
      cables_detail: [
        'MIL-W-22759 PTFE/ETFE silver wire (200°C)',
        'M22759 cross-linked ETFE aircraft wire',
        'MIL-C-27500 multi-conductor shielded',
        'ARINC 429 twisted shielded pair (78Ω)',
        'MIL-STD-1553 twinaxial cable (70.5Ω)',
        'Aviation fibre optic (ARINC 664)',
      ],
      standards: ['MIL-DTL-38999', 'DO-160G', 'AS9100D', 'MIL-STD-1553', 'ARINC 429', 'MIL-STD-810'],
      useCases: [
        'Fighter jet avionics bay wiring',
        'Commercial airliner fly-by-wire harness',
        'UAV/drone mission computer connections',
        'Missile guidance signal interface',
        'Satellite on-board electronics interconnects',
      ],
    },

    {
      id: 'marine-maritime',
      name: 'Marine & Maritime',
      icon: '⚓',
      sector: 'Transportation & Automotive',
      filter: 'transport',
      accentColor: '#0ea5e9',
      colorA: 'rgba(14,165,233,0.08)',
      colorB: 'transparent',
      cables: ['IP68 Subconn', 'NMEA 2000', 'MacArtney', 'Wet-Mate', 'IEC 60092'],
      specs: ['IP68', 'ROV Rated', 'Saltwater'],
      connectorCount: 13,
      description: 'Marine environments expose connectors to saltwater corrosion, high hydrostatic pressures (ROV systems to 6000m depth), UV, and biofouling. IEC 60092 governs shipboard electrical installations. Subsea connectors use titanium or hard anodized aluminium bodies with double O-ring seals. NMEA 2000 is the standard marine data network.',
      connectors: [
        { name: 'SUBCONN Circular (Cobalt)', application: 'ROV umbilical, underwater camera', ipRating: 'IP68 6000m', standard: 'IEC 60068-2-68' },
        { name: 'Wet-Mate (MacArtney)', application: 'Subsea hot-stab wet mating', ipRating: '6000m rated', standard: 'DNV-RP-0401' },
        { name: 'NMEA 2000 Micro-C', application: 'Marine instrument bus (GPS, AIS, chart)', ipRating: 'IP67', standard: 'NMEA 2000' },
        { name: 'Mil-spec Circular (Al)', application: 'Deck/engine room instrument panels', ipRating: 'IP66', standard: 'IEC 60309' },
        { name: 'GLAND-IP68 (PG-series)', application: 'Topside cable penetration, deck boxes', ipRating: 'IP68', standard: 'IEC 60529' },
        { name: 'IEC 60309 (CEE 63A)', application: 'Shore power (230/400V)', ipRating: 'IP44', standard: 'IEC 60309' },
      ],
      cables_detail: [
        'IEC 60092-376 armoured shipboard cable',
        'Subsea umbilical (power + fibre + hydraulic)',
        'NMEA 2000 DeviceNet compatible cable',
        'Halogen-free marine LSZH cable',
        'Tin-bronze wire armoured marine cable',
      ],
      standards: ['IEC 60092', 'NMEA 2000', 'DNV GL', 'Lloyd\'s Register', 'SOLAS'],
      useCases: [
        'ROV to surface tether/umbilical',
        'Bridge navigation electronics',
        'Diving habitat/pressure housing connections',
        'Sonar transducer array',
        'Offshore platform instrumentation cables',
      ],
    },

  ],

  energy: [

    {
      id: 'oil-gas',
      name: 'Oil & Gas (Upstream/Downstream)',
      icon: '🛢️',
      sector: 'Energy & Environment',
      filter: 'energy',
      accentColor: '#854d0e',
      colorA: 'rgba(133,77,14,0.08)',
      colorB: 'transparent',
      cables: ['Armoured Inst.', 'ATEX Plug', 'Thermocouple', 'MUD-resistant', 'BNC/TNC'],
      specs: ['ATEX Zone 0', 'IP68', 'H2S Resist.'],
      connectorCount: 14,
      description: 'Upstream oil and gas operations span offshore rigs, downhole tools, and pipeline SCADA. ATEX Zone 0 (gas continuously present) to Zone 2 areas require explosion-proof or intrinsically safe (Ex-i) certified connectors. Downhole logging tools (MWD/LWD) experience pressures >10,000 psi and temperatures exceeding 200°C.',
      connectors: [
        { name: 'ATEX Ex-d Plug (3-Ph)', application: 'Zone 1 explosion-proof pump starter', ipRating: 'IP66', standard: 'IEC 60079-1' },
        { name: 'IS Zener Barrier Term.', application: 'Zone 0 intrinsically safe field junction', ipRating: 'IP65', standard: 'IEC 60079-11' },
        { name: 'Kemlon (150°C Epoxy)', application: 'Downhole MWD/LWD probe connector', ipRating: '200°C/15kpsi', standard: 'API RP 7G' },
        { name: 'MWX (High-Temp Coax)', application: 'Well logging cable coax termination', ipRating: '250°C', standard: 'API 11V1' },
        { name: 'BNC/N-type RF (ATEX)', application: 'Topside telemetry antenna', ipRating: 'IP65', standard: 'IEC 60079-7' },
        { name: 'Stainless AISI 316L M12', application: 'Offshore platform sensor nodes', ipRating: 'IP68', standard: 'NORSOK M-501' },
      ],
      cables_detail: [
        'SWA/SWB Armoured instrument cable',
        'Mining/well logging armoured coax (EPDM)',
        'H2S-resistant polyamide 11 sheathed',
        'ATEX-rated flexible power cable',
        'Mineral insulated (MI) fireproof cable (IEC 60702)',
      ],
      standards: ['ATEX 2014/34/EU', 'IEC 60079', 'IECEx', 'API RP 505', 'NORSOK Z-010'],
      useCases: [
        'Wellhead Christmas tree instrumentation',
        'FPSO process control (PCS) wiring',
        'Pipeline cathodic protection monitoring',
        'Flare tip thermocouple connections',
        'Subsea wellhead (wet-mate subsea)',
      ],
    },

    {
      id: 'power-utilities',
      name: 'Power Generation & Utilities',
      icon: '🏭',
      sector: 'Energy & Environment',
      filter: 'energy',
      accentColor: '#fbbf24',
      colorA: 'rgba(251,191,36,0.07)',
      colorB: 'transparent',
      cables: ['XLPE MV/HV', 'IEC 61850', 'CT/VT Pilot', 'Bus-duct Conn.', 'Fiber IEC'],
      specs: ['IEC 61850', '33kV+', 'Type-tested'],
      connectorCount: 10,
      description: 'Electricity transmission, distribution, and generation (thermal, hydro, nuclear) plants use medium- and high-voltage XLPE cables and IEC 61850-compliant digital substations. Protection relay systems use screened pilot cables for CT/VT connections. Substations increasingly use hardened fiber optic for IEC 61850 process bus.',
      connectors: [
        { name: 'HV Screened (RXPE Joint)', application: 'Cable joints for 33–400kV XLPE', ipRating: 'IP68', standard: 'IEC 60840' },
        { name: 'IEC 61850 Switched RJ45', application: 'Substation process bus (GOOSE)', ipRating: 'IP20', standard: 'IEC 61850' },
        { name: 'EP-Type CT/VT Terminal', application: 'Current/voltage transformer secondary', ipRating: 'IP20', standard: 'IEC 61869' },
        { name: 'SF6 Gas-insulated (GIS) Conn.', application: 'Gas insulated switchgear busbar', ipRating: 'IP67', standard: 'IEC 62271-203' },
        { name: 'T-series (Ensto) Insert', application: 'Medium voltage elbow/separable', ipRating: 'IP65', standard: 'IEC 60502-4' },
      ],
      cables_detail: [
        'XLPE 3-core armoured cable (11–400kV)',
        'Mineral insulated fireproof cable',
        'IEC 61850 type-tested multipair cable',
        'Oil-impregnated paper (SCPB) HV cable',
        'Pilot protection cable (screened pair)',
      ],
      standards: ['IEC 61850', 'IEC 60840', 'IEC 62271', 'IEEE C57', 'NERC CIP'],
      useCases: [
        'Substation protection relay wiring',
        'Nuclear plant I&C instrument cables',
        'Hydro generator excitation cables',
        'Smart meter communication (RF mesh)',
        'SCADA RTU communications',
      ],
    },

    {
      id: 'renewable-energy',
      name: 'Renewable Energy (Solar & Wind)',
      icon: '☀️',
      sector: 'Energy & Environment',
      filter: 'energy',
      accentColor: '#22c55e',
      colorA: 'rgba(34,197,94,0.08)',
      colorB: 'transparent',
      cables: ['MC4 PV', 'H1Z2Z2-K', 'Offshore Wind HV', 'IEC 62548', 'WTG Power'],
      specs: ['IEC 62852', 'UV Resist', 'TÜV Rheinland'],
      connectorCount: 11,
      description: 'Solar PV systems use the MC4 (Multi-Contact 4mm) connector as the de facto standard for string interconnection and module-to-string connections. The IEC 62852 standard governs DC PV connectors. Wind turbines use medium-voltage slip rings and generator cable routing systems that must withstand torsion (full 360° nacelle rotation).',
      connectors: [
        { name: 'MC4 (Multi-Contact)', application: 'PV module string interconnect (1–1500V DC)', ipRating: 'IP67', standard: 'IEC 62852' },
        { name: 'MC4-Evo 2', application: 'New-generation PV connector (1500V DC)', ipRating: 'IP68', standard: 'IEC 62852' },
        { name: 'T4 Solar (Amphenol)', application: 'Utility-scale PV junction boxes', ipRating: 'IP67', standard: 'IEC 62852' },
        { name: 'MV Wind Slip Ring', application: 'Wind turbine tower-to-nacelle power', ipRating: 'IP54', standard: 'IEC 61400-24' },
        { name: 'SMA Sunny Inverter Port', application: 'String inverter AC output terminals', ipRating: 'IP20', standard: 'IEC 62477' },
        { name: 'SUNCLIX (Phoenix)', application: 'Inverter DC input strings', ipRating: 'IP2X', standard: 'IEC 62852' },
      ],
      cables_detail: [
        'H1Z2Z2-K PV cable (UV/ozone/weather resistant)',
        'TÜV-approved 6mm² PV string cable',
        'XLPE 33kV offshore wind export cable',
        'Wind turbine tower torsion cable (halogen-free)',
        'Offshore submarine inter-array cable (66kV)',
      ],
      standards: ['IEC 62852', 'IEC 61730', 'IEC 61400-24', 'TÜV 2 PfG 1169', 'UL 4703'],
      useCases: [
        'Rooftop solar panel string wiring',
        'Utility-scale ground mount PV arrays',
        'Floating solar (agri-PV) installations',
        'Onshore/offshore wind farm collector grids',
        'Battery energy storage (BESS) DC links',
      ],
    },

    {
      id: 'water-wastewater',
      name: 'Water & Wastewater Management',
      icon: '💧',
      sector: 'Energy & Environment',
      filter: 'energy',
      accentColor: '#0ea5e9',
      colorA: 'rgba(14,165,233,0.06)',
      colorB: 'transparent',
      cables: ['M12 Submersible', 'IP68 Pump', 'EMC Signal', 'LSZH Sewer', 'Cat5e FTP'],
      specs: ['IP68', 'Chlorine Resist', 'Buried Rated'],
      connectorCount: 9,
      description: 'Water treatment plants, pumping stations, and sewerage systems use submersible sensors and pumps operating continuously in corrosive chemical environments. Cable insulation must resist chlorine, chloramines, and H2S gases common in sewers. Buried cables need armoured protection.',
      connectors: [
        { name: 'M12 Submersible IP68', application: 'Level sensors, submersible pump', ipRating: 'IP68 (10m)', standard: 'IEC 61076-2-101' },
        { name: 'CEE 16A IEC 60309', application: 'Portable pump set power supply', ipRating: 'IP67', standard: 'IEC 60309' },
        { name: 'Watertight Cable Gland (A2)', application: 'Control panel cable entry (outdoor)', ipRating: 'IP68', standard: 'IEC 60529' },
        { name: 'D-Sub 9 RS-485 Term.', application: 'Modbus RTU flow meter comms', ipRating: 'IP20', standard: 'EIA-485' },
        { name: 'GPRS/4G SMA Antenna', application: 'Remote SCADA telemetry from booster stn', ipRating: 'IP67', standard: 'IEC 60529' },
      ],
      cables_detail: [
        'MDPE armoured submersible pump cable',
        'PVC water utility distribution cable',
        'LSZH control cable for pump house',
        'Direct-burial underground cable (rated 90°C wet)',
        'HART-compatible screened instrument cable',
      ],
      standards: ['IEC 60529', 'IEC 60309', 'WRAS Approved', 'NSF/ANSI 61', 'BS EN 60086'],
      useCases: [
        'Borehole submersible pump wiring',
        'Water tower level telemetry',
        'Effluent flow meter Modbus connection',
        'Dam gate actuator control cable',
        'Chemical dosing pump signal loop',
      ],
    },

  ],

  tech: [

    {
      id: 'telecom-datacom',
      name: 'Telecom & Broadband Networks',
      icon: '📡',
      sector: 'Technology & Communications',
      filter: 'tech',
      accentColor: '#a855f7',
      colorA: 'rgba(168,85,247,0.08)',
      colorB: 'transparent',
      cables: ['LC/SC/MPO Fiber', 'Cat8 S/FTP', 'Coax RG-6', 'CPRI Fiber', 'LMR-400'],
      specs: ['10GBase-T', 'OM5 Fiber', 'Low-loss RF'],
      connectorCount: 18,
      description: 'Telecom networks—from the core to last-mile access—rely on single-mode fibre optic for long-haul, with LC/SC/MTP connectors. 5G base stations use CPRI/eCPRI fibre fronthaul. Distribution frames use MPO-24 trunk cables. In-building networks (DAS) use LMR-400 low-loss coaxial cables to remote antenna units.',
      connectors: [
        { name: 'LC Duplex (UPC/APC)', application: 'DWDM transponders, SFP+ modules', ipRating: 'IP20', standard: 'IEC 61754-20' },
        { name: 'SC/APC (Green boot)', application: 'PON GPON/XGS-PON splitter ports', ipRating: 'IP20', standard: 'IEC 61754-4' },
        { name: 'MPO-12/MPO-24 (MTP®)', application: 'Spine-leaf spine trunks, 40/100G', ipRating: 'IP20', standard: 'IEC 61754-7' },
        { name: 'E2000/LX.5', application: 'Central office high-density ODF', ipRating: 'IP50', standard: 'IEC 61754-15' },
        { name: 'N-type 50Ω', application: 'Base station RF coax (4G/5G)', ipRating: 'IP65', standard: 'IEC 61169-16' },
        { name: '4.3-10 Coax', application: 'Small cell 5G mmWave connections', ipRating: 'IP67', standard: 'DIN EN 116522' },
        { name: 'DIN 7-16', application: 'Macro BTS antenna port', ipRating: 'IP65', standard: 'DIN 47295' },
      ],
      cables_detail: [
        'OS2 G.654.E single-mode low-loss fibre',
        'OM5 wideband multimode (SWDM4)',
        'Cat8.1 S/FTP (40GBase-T)',
        'LMR-400 50Ω coax (DAS/ERRCS)',
        'CPRI eCPRI fibre fronthaul jumper',
      ],
      standards: ['ITU-T G.652D', 'IEC 61754', 'TIA-568.3-D', 'IEEE 802.3', '3GPP eCPRI'],
      useCases: [
        '5G small cell fronthaul (eCPRI)',
        'Data center inter-rack DWDM links',
        'FTTH/GPON subscriber drop cables',
        'In-building DAS antenna runs',
        'Submarine cable landing station termination',
      ],
    },

    {
      id: 'data-centers',
      name: 'Data Centers & Cloud Computing',
      icon: '🖥️',
      sector: 'Technology & Communications',
      filter: 'tech',
      accentColor: '#6366f1',
      colorA: 'rgba(99,102,241,0.08)',
      colorB: 'transparent',
      cables: ['MPO-24 OM5', 'DAC SFP', 'Cat6A U/FTP', '400G QSFP', 'APC Fiber'],
      specs: ['400GbE', 'ANSI/TIA-942', 'Tier III'],
      connectorCount: 15,
      description: 'Hyperscale data centers demand extremely high-density, low-latency interconnects. Direct Attach Copper (DAC) cables support short 100G/400G rack-to-rack links. Structured cabling uses MPO-24 pre-terminated trunks for rapid deployment. Power distribution relies on C13/C19/IEC 60320 plugs on PDUs and rack UPS units.',
      connectors: [
        { name: 'QSFP-DD 8-lane 400G', application: 'Spine switch 400GbE ports', ipRating: 'IP20', standard: 'QSFP-DD MSA' },
        { name: 'MPO-16/24 APC', application: '400G-SR16 multimode parallel optic', ipRating: 'IP20', standard: 'IEC 61754-7' },
        { name: 'LC UPC SFP28 25G', application: 'Server NIC to ToR switch', ipRating: 'IP20', standard: 'SFP28 MSA' },
        { name: 'C13/C19 IEC 60320', application: 'PDU to server power strips', ipRating: 'IP20', standard: 'IEC 60320' },
        { name: 'RJ45 Cat6A (Shielded)', application: 'IPMI/BMC out-of-band management', ipRating: 'IP20', standard: 'TIA-568.2-D' },
        { name: 'SAS-4 (SFF-8643)', application: 'NVMe/SAS storage backplane', ipRating: 'IP20', standard: 'SFF-8643' },
      ],
      cables_detail: [
        '400G DAC QSFP-DD twinax (1–5m)',
        'MPO-24 OM4 pre-term trunk cable',
        'Cat6A U/FTP 28AWG slim patch cord',
        '2kV industrial PDU power cord',
        '200G/400G AOC (Active Optical Cable)',
      ],
      standards: ['ANSI/TIA-942-B', 'IEEE 802.3bs', 'QSFP-DD MSA', 'IEC 62040', 'Uptime Tier III'],
      useCases: [
        'Hyperscale spine-leaf Clos fabric',
        'AI/GPU cluster NVLink interconnect',
        'Colocation cross-connect fiber panels',
        'Rack PDU C19/C13 power distribution',
        'KVM over IP out-of-band management',
      ],
    },

    {
      id: 'consumer-electronics',
      name: 'Consumer Electronics & AV',
      icon: '📱',
      sector: 'Technology & Communications',
      filter: 'tech',
      accentColor: '#ec4899',
      colorA: 'rgba(236,72,153,0.07)',
      colorB: 'transparent',
      cables: ['USB4 Type-C', 'HDMI 2.1', 'DisplayPort 2.1', 'Lightning', 'Thunderbolt 4'],
      specs: ['USB PD 3.1', 'HDMI 2.1 48G', '8K Ready'],
      connectorCount: 16,
      description: 'Consumer electronics use a rapidly evolving set of universal connectors. USB Type-C is converging on a single universal port for power delivery (up to 240W with EPR), data (USB 3.2/USB4), and display (DisplayPort ALT mode). HDMI 2.1 supports 48 Gbps for 8K/120Hz. Thunderbolt 4 provides 40 Gbps bidirectional with daisy-chaining.',
      connectors: [
        { name: 'USB Type-C (USB4 Gen 3×2)', application: 'Universal 40Gbps + 240W PD port', ipRating: 'IP20', standard: 'USB4 v2.0' },
        { name: 'HDMI 2.1 Type-A', application: '8K60/4K120 display output', ipRating: 'IP20', standard: 'HDMI 2.1' },
        { name: 'DisplayPort 2.1 (UHBR20)', application: '16K display, multi-stream', ipRating: 'IP20', standard: 'VESA DP 2.1' },
        { name: 'Thunderbolt 4', application: 'Dock station, external GPU', ipRating: 'IP20', standard: 'Intel TB4' },
        { name: '3.5mm TRRS (CTIA)', application: 'Headphone + microphone combo', ipRating: 'IP20', standard: 'CTIA-AG02' },
        { name: 'XLR 3-pin', application: 'Professional balanced audio (studio)', ipRating: 'IP20', standard: 'IEC 61076-2-103' },
        { name: 'HDMI eARC', application: 'Sound bar / AV receiver digital audio', ipRating: 'IP20', standard: 'HDMI 2.1' },
      ],
      cables_detail: [
        'USB4 40Gbps active optical cable',
        'Ultra High Speed HDMI 48Gbps cable',
        'Thunderbolt 4 passive 1m copper',
        'DisplayPort 2.1 UHBR20 cable',
        'Oxygen-free copper (OFC) audiophile RCA',
      ],
      standards: ['USB4 v2.0', 'HDMI 2.1', 'DP 2.1', 'IEC 62680', 'IEEE 1394'],
      useCases: [
        'Laptop USB-C multiport hub',
        '8K gaming monitor cable chain',
        'Studio reference monitor XLR wiring',
        'Smart TV HDMI 2.1 connection',
        'Pro camera USB4 recording link',
      ],
    },

    {
      id: 'machine-vision',
      name: 'Machine Vision & Imaging',
      icon: '👁️',
      sector: 'Technology & Communications',
      filter: 'tech',
      accentColor: '#14b8a6',
      colorA: 'rgba(20,184,166,0.07)',
      colorB: 'transparent',
      cables: ['Camera Link', 'CoaXPress', 'GigE Vision', '10GigE SFP', 'M12 X-Code'],
      specs: ['CoaXPress 2.0', 'USB3 Vision', '100GigE'],
      connectorCount: 10,
      description: 'Industrial machine vision cameras require very high bandwidth links with zero latency and camera power over the cable. CoaXPress 2.0 delivers 12.5 Gbps per lane over 75Ω coax with 13W power. GigE Vision over M12 X-Code is used for networked camera arrays. Camera Link uses MDR/SDR 26-pin connectors for multi-lane parallel transfer.',
      connectors: [
        { name: 'BNC (75Ω CoaXPress)', application: 'CoaXPress 2.0 camera link (12.5G/lane)', ipRating: 'IP20', standard: 'JIIA CXP-001' },
        { name: 'M12 X-Code (8-pin)', application: 'GigE Vision 1GbE camera', ipRating: 'IP67', standard: 'IEC 61076-2-109' },
        { name: 'Camera Link MDR 26-pin', application: 'High-speed parallel camera bus', ipRating: 'IP20', standard: 'Camera Link Std' },
        { name: 'USB3 Vision Micro-B', application: '5Gbps USB3 area-scan camera', ipRating: 'IP20', standard: 'USB3 Vision v1.0' },
        { name: 'SFP+ (LC) 10GbE', application: '10GigE Vision line-scan camera', ipRating: 'IP20', standard: 'IEEE 802.3ae' },
      ],
      cables_detail: [
        '75Ω RG-6 low-loss CoaXPress coax',
        'Cat5e/Cat6A GigE Vision patch cord',
        'Camera Link MDR-MDR screened cable',
        'USB3 10m active optical cable (AOC)',
        'HDMI 4K camera monitor cable',
      ],
      standards: ['CoaXPress 2.0', 'GigE Vision', 'USB3 Vision', 'Camera Link', 'GenICam'],
      useCases: [
        'PCB solder joint inspection cameras',
        'High-speed web inspection (10m/s+)',
        'Robotics bin picking vision system',
        'Medical endoscope imaging module',
        'Traffic speed ANPR camera',
      ],
    },

  ],

  healthcare: [

    {
      id: 'medical-imaging',
      name: 'Medical Imaging & Diagnostics',
      icon: '🏥',
      sector: 'Healthcare & Science',
      filter: 'healthcare',
      accentColor: '#ec4899',
      colorA: 'rgba(236,72,153,0.08)',
      colorB: 'transparent',
      cables: ['LEMO 1B/2B', 'MRI-safe Coax', 'Push-Pull', 'USB3 Medical', 'FO MRI'],
      specs: ['IEC 60601-1', 'MRI RF Safe', 'Biocompatible'],
      connectorCount: 12,
      description: 'Medical imaging equipment (MRI, CT, X-ray, ultrasound) demands connectors with zero risk of patient electrical shock. IEC 60601-1 limits leakage currents to 10µA for CF-rated patient-applied parts. MRI environments introduce RF interference and strong magnetic fields, requiring non-ferromagnetic LEMO push-pull connectors. All materials in contact with patients must be biocompatible per ISO 10993.',
      connectors: [
        { name: 'LEMO 1B (Push-Pull)', application: 'ECG, EEG, patient monitoring', ipRating: 'IP50', standard: 'IEC 60601-1' },
        { name: 'LEMO 2B (Large Push-Pull)', application: 'Ultrasound probe array connector', ipRating: 'IP50', standard: 'IEC 60601-1' },
        { name: 'MRI RF Coil Connector', application: 'MRI receive coil array connection', ipRating: 'IP20', standard: 'IEC 60601-2-33' },
        { name: 'Hirose HR10A (Push-Lock)', application: 'Endoscope camera head connection', ipRating: 'IP67', standard: 'ISO 10993' },
        { name: 'ODU AMC (Auto-Mating)', application: 'Surgical robot wrist instrument', ipRating: 'IP67', standard: 'IEC 60601-1' },
        { name: 'D3120 Medical Power (IEC 60320)', application: 'Medical device C13/C14 mains input', ipRating: 'IP20', standard: 'IEC 60320' },
      ],
      cables_detail: [
        'MRI-compatible fibre optic signal cable',
        'Silicone-jacketed patient lead wire',
        'Shielded LSZH medical device cable',
        'Autoclave-sterilizable PTFE cables',
        'ECG snap electrode lead (silver-silver chloride)',
      ],
      standards: ['IEC 60601-1', 'IEC 60601-2-33', 'ISO 10993', 'FDA 21 CFR 880', 'ASTM F2503'],
      useCases: [
        'MRI surface receive coil array',
        'CT scanner slip ring power transfer',
        'Ultrasound transducer array wiring',
        'Surgical robot tool interface connectors',
        'X-ray detector flat panel links',
      ],
    },

    {
      id: 'patient-monitoring',
      name: 'Patient Monitoring & Nursing',
      icon: '💉',
      sector: 'Healthcare & Science',
      filter: 'healthcare',
      accentColor: '#f43f5e',
      colorA: 'rgba(244,63,94,0.07)',
      colorB: 'transparent',
      cables: ['DIN 42802 ECG', 'SpO2 DB9', 'NIBP Tubing', 'Patient Data USB', 'LEMO 0B'],
      specs: ['CF Type', 'Defibrillation-proof', 'IEC 60601'],
      connectorCount: 9,
      description: 'Bedside monitors, ventilators, infusion pumps, and defibrillators interface directly with patients. All patient-connected leads must be classified as CF (Cardiac Float) rated for defibrillation-proof protection (5kV surge per IEC 60601). Anti-microbial coatings on cable jackets reduce hospital-acquired infections.',
      connectors: [
        { name: 'DIN 42802 (ECG Snap/Banana)', application: '4/5/10-lead ECG patient cables', ipRating: 'IP20', standard: 'DIN 42802' },
        { name: 'DB9 (SpO2 Masimo/Nellcor)', application: 'Pulse oximetry probe to monitor', ipRating: 'IP20', standard: 'AAMI EC53' },
        { name: 'LEMO 0B 3-pin', application: 'Temperature probe patient connection', ipRating: 'IP50', standard: 'IEC 60601-1' },
        { name: 'USB-A 2.0 (Medical)', application: 'Data download, nurse call panel', ipRating: 'IP20', standard: 'USB 2.0' },
        { name: 'RJ11 (NIBP Hose Valve)', application: 'Non-invasive blood pressure tubing lock', ipRating: 'IP20', standard: 'AAMI SP10' },
      ],
      cables_detail: [
        'ECG lead wire (PVC, 1.5m, snap ends)',
        'SpO2 extension cable (with optical fibre)',
        'Defibrillation-proof patient cable',
        'Anti-microbial PVC jacketed nurse-call wire',
        'Low-capacitance EEG lead cable',
      ],
      standards: ['IEC 60601-1-6', 'AAMI EC53', 'AAMI SP10', 'IEC 60601-2-27', 'UL 2601-1'],
      useCases: [
        'ICU bedside multi-parameter monitor',
        'Ambulatory Holter ECG recorder',
        'Defibrillator paddle connection',
        'Neonatal SpO2 wrap sensor',
        'Operating theatre patient temp probe',
      ],
    },

    {
      id: 'test-measurement',
      name: 'Test & Measurement',
      icon: '📏',
      sector: 'Healthcare & Science',
      filter: 'healthcare',
      accentColor: '#f97316',
      colorA: 'rgba(249,115,22,0.07)',
      colorB: 'transparent',
      cables: ['BNC 50Ω', 'SMA', 'GPIB (IEEE-488)', 'Kelvin 4-wire', 'Triaxial'],
      specs: ['50GHz', 'VSWR <1.1', '6-digit DVM'],
      connectorCount: 14,
      description: 'Oscilloscopes, spectrum analyzers, signal generators, DMMs, and parametric analyzers rely on precision connectors with extremely low reflection (VSWR <1.05) and calibrated characteristic impedance. High-frequency measurements to 110 GHz use 1.85mm (V-connector) or 1mm connectors. GPIB (IEEE-488) is the classic instrument bus.',
      connectors: [
        { name: 'BNC (50Ω)', application: 'General RF, oscilloscope probe', ipRating: 'IP20', standard: 'IEC 61169-8' },
        { name: 'SMA (3.5mm compatible)', application: 'Microwave to 26.5 GHz', ipRating: 'IP20', standard: 'MIL-STD-348' },
        { name: '2.92mm (K-connector)', application: 'Millimeter wave to 46 GHz', ipRating: 'IP20', standard: 'MIL-STD-348' },
        { name: '1.85mm (V-connector)', application: 'W-band measurements to 67 GHz', ipRating: 'IP20', standard: 'IEEE 1785' },
        { name: 'GPIB 24-pin (IEEE-488)', application: 'Instrument bus control', ipRating: 'IP20', standard: 'IEEE-488.2' },
        { name: 'Triax BNC / Triaxial', application: 'Low-current source measure (SMU)', ipRating: 'IP20', standard: 'IEC 60603-3' },
        { name: 'Banana 4mm Safety', application: 'DMM probe, bench power supply', ipRating: 'IP20', standard: 'IEC 61010-031' },
      ],
      cables_detail: [
        'Low-loss RG-316 50Ω microwave coax',
        'Precision 3.5mm SMA test cable (1m)',
        'GPIB 24-pin shielded bus cable',
        'Kelvin 4-wire sense cable (0.01% accuracy)',
        'Semi-rigid 0.141" Cu-Cu coax (0–26.5 GHz)',
      ],
      standards: ['IEEE 488.2', 'IEC 61169', 'MIL-STD-348', 'TDR Z0=50Ω', 'NIST traceable'],
      useCases: [
        'Oscilloscope probe to DUT (Device Under Test)',
        'VNA S-parameter measurement cables',
        'RF power meter N-type connections',
        'SMU semiconductor parameter test',
        'EMC immunity/emission test setups',
      ],
    },

  ],

  infrastructure: [

    {
      id: 'building-automation',
      name: 'Building Automation & HVAC',
      icon: '🏢',
      sector: 'Infrastructure, Agriculture & Others',
      filter: 'infrastructure',
      accentColor: '#14b8a6',
      colorA: 'rgba(20,184,166,0.07)',
      colorB: 'transparent',
      cables: ['KNX/EIB', 'BACnet/IP', 'Modbus RTU', 'Cat6 STP', 'DALI 2'],
      specs: ['BACnet', 'KNX Certified', 'LSZH'],
      connectorCount: 10,
      description: 'Building management systems (BMS) control HVAC, lighting, access control, and energy management using BACnet, KNX, or LON fieldbus protocols. KNX uses a dedicated 0.8mm twisted pair for combined power and data. Modern smart buildings adopt BACnet/IP over standard Cat5e/Cat6 networks. Fire alarm cabling must meet EN 50200 circuit integrity under fire.',
      connectors: [
        { name: 'KNX/EIB 2-wire Push-In', application: 'BMS sensor, actuator, room controller', ipRating: 'IP20', standard: 'EN 50090' },
        { name: 'RJ45 Cat6 (BACnet/IP)', application: 'BACnet/IP building controller network', ipRating: 'IP20', standard: 'ANSI/ASHRAE 135' },
        { name: 'DALI 2 Terminal Block', application: 'Digital addressable lighting interface', ipRating: 'IP20', standard: 'IEC 62386' },
        { name: 'Modbus RS-485 (Wago)', application: 'Modbus RTU HVAC equipment', ipRating: 'IP20', standard: 'EIA-485' },
        { name: 'RJ12 / RJ11', application: 'Room sensor (temp/humidity) to DDC', ipRating: 'IP20', standard: 'TIA-568' },
      ],
      cables_detail: [
        'KNX green sheathed 2×0.8mm twisted pair',
        'DALI 2-core unscreened 1.5mm²',
        'CIR (fire-resistant) alarm cable EN 50200',
        'Cat6 STP (building Ethernet backbone)',
        'LSZH 2-pair screened data cable',
      ],
      standards: ['EN 50090 (KNX)', 'ANSI/ASHRAE 135', 'IEC 62386 (DALI)', 'EN 54 (fire)', 'ISO 16484'],
      useCases: [
        'Smart office HVAC zone control',
        'Hotel room lighting/curtain automation',
        'Chiller plant energy optimization',
        'Access control card reader wiring',
        'CO2 demand-controlled ventilation',
      ],
    },

    {
      id: 'traffic-infrastructure',
      name: 'Intelligent Traffic Systems',
      icon: '🚦',
      sector: 'Infrastructure, Agriculture & Others',
      filter: 'infrastructure',
      accentColor: '#16a34a',
      colorA: 'rgba(22,163,74,0.07)',
      colorB: 'transparent',
      cables: ['Fiber ITS', 'Loop Detector', 'IP67 M12', 'NEMA TS2', 'ATC IEEE'],
      specs: ['NEMA TS2', 'IEC 60068 Traffic', 'IP67'],
      connectorCount: 8,
      description: 'Intelligent transportation systems (ITS) encompass traffic signals, variable message signs (VMS), ANPR cameras, and pedestrian detection. Underground loop detector cables withstand road surface temperatures and vehicle crush loads. Communications follow NEMA TS2 or NTCIP standards. CCTV poles use weatherproof Bulgin or IP67 M12 connectors.',
      connectors: [
        { name: 'NEMA TS2 Type 2 Connector', application: 'Traffic controller cabinet I/O', ipRating: 'IP44', standard: 'NEMA TS 2-2016' },
        { name: 'IP67 M12 (A-Code)', application: 'Traffic detector, induction loop', ipRating: 'IP67', standard: 'IEC 61076' },
        { name: 'Bulgin 4000 Series', application: 'Roadside cabinet power/signal', ipRating: 'IP66/68', standard: 'IEC 60529' },
        { name: 'LC Fiber (OS2)', application: 'CCTV fiber uplink to TMC', ipRating: 'IP20', standard: 'IEC 61754-20' },
        { name: 'DB15 (VGA-style ITS)', application: 'Variable message sign control', ipRating: 'IP20', standard: 'NTCIP 1203' },
      ],
      cables_detail: [
        'XLPE loop detector cable (high-temp road)',
        'Armoured OS2 singlemode ITS fiber',
        'XLPE/PVC signal cable (street cabinet)',
        'LSZH armoured CCTV cable',
        'Cat5e FTP cabinet-to-camera Ethernet',
      ],
      standards: ['NEMA TS2', 'NTCIP', 'IEEE 802.11p (DSRC)', 'IEC 60529', 'EN 50556'],
      useCases: [
        'Traffic signal controller wiring',
        'Highway ANPR speed camera cable',
        'Pedestrian crossing push-button',
        'VMS dynamic display fiber link',
        'Smart city IoT sensor pole',
      ],
    },

    {
      id: 'agriculture-iot',
      name: 'Agriculture & Smart Farming',
      icon: '🌾',
      sector: 'Infrastructure, Agriculture & Others',
      filter: 'infrastructure',
      accentColor: '#65a30d',
      colorA: 'rgba(101,163,13,0.07)',
      colorB: 'transparent',
      cables: ['IP67 M12', 'LoRa SMA', 'UV Cable', 'Deutsch HD30', 'ISOBUS'],
      specs: ['ISOBUS', 'IP67', 'UV Stabilised'],
      connectorCount: 9,
      description: 'Modern agriculture uses GPS guidance, variable rate applicators, drone surveying, and IoT soil sensors across large outdoor areas. Farm machinery follows the ISOBUS (ISO 11783) standard based on CAN J1939. Connectors must survive UV, chemicals (fertilizer, pesticide), mud, and vibration from rough terrain.',
      connectors: [
        { name: 'ISOBUS (DIN 9684-1) 7-pin', application: 'Tractor-implement ISOBUS data/power', ipRating: 'IP67', standard: 'ISO 11783-2' },
        { name: 'Deutsch HD30 Series', application: 'Combine harvester main harness', ipRating: 'IP67', standard: 'USCAR-12' },
        { name: 'DT (2/3/4-pin, Deutsch)', application: 'Field sensor, valve blocks', ipRating: 'IP67', standard: 'USCAR-2' },
        { name: 'SMA (LoRa/GNSS)', application: 'IoT gateway GNSS/LPWAN antenna', ipRating: 'IP67', standard: 'SMA Mil' },
        { name: 'M12 A-Code IP67', application: 'Irrigation sensor node', ipRating: 'IP67', standard: 'IEC 61076' },
      ],
      cables_detail: [
        'ISOBUS yellow CAN cable (shielded)',
        'UV-stabilised PE insulated cable',
        'Chemical-resistant polyamide cable',
        'Flexible rubber multicore (farm machinery)',
        'LoRaWAN LMR-195 low-loss antenna cable',
      ],
      standards: ['ISO 11783 (ISOBUS)', 'SAE J1939', 'IEC 61508 (SIL ag)', 'LoRaWAN Spec', 'IEC 60529'],
      useCases: [
        'GPS auto-steer tractor implement link',
        'Variable rate sprayer section control',
        'Drone base-station RTK GNSS',
        'Soil moisture sensor wireless node',
        'Grain elevator scale indicator CAN',
      ],
    },

    {
      id: 'broadcasting',
      name: 'Broadcasting & Entertainment',
      icon: '🎬',
      sector: 'Infrastructure, Agriculture & Others',
      filter: 'infrastructure',
      accentColor: '#d946ef',
      colorA: 'rgba(217,70,239,0.07)',
      colorB: 'transparent',
      cables: ['12G-SDI BNC', 'Socapex 19-pin', 'NL8 Neutrik', 'XLR AES/EBU', 'HDMI 2.1'],
      specs: ['12G-SDI', 'AES3 110Ω', 'IEC 60268'],
      connectorCount: 13,
      description: 'Broadcast and live entertainment require extremely reliable, quick-connect/disconnect connectors that can be deployed rapidly in outdoor venues and stadiums. 12G-SDI BNC supports uncompressed 4K video over a single coaxial cable. Socapex multi-cable systems distribute power to stage lighting rigs. Neutrik connectors dominate in professional audio and video.',
      connectors: [
        { name: 'BNC 75Ω (12G-SDI)', application: '4K SDI video signal (12 Gbps)', ipRating: 'IP20', standard: 'SMPTE ST 2082' },
        { name: 'XLR 3-pin (Neutrik)', application: 'Balanced audio, AES/EBU digital', ipRating: 'IP20', standard: 'IEC 61076-2-103' },
        { name: 'Socapex 19-pin', application: 'Multi-circuit stage lighting power', ipRating: 'IP44', standard: 'IEC 60309' },
        { name: 'NL8 SpeakON (Neutrik)', application: '8-pole loudspeaker power (high amp)', ipRating: 'IP20', standard: 'IEC 61076' },
        { name: 'etherCON RJ45 (Neutrik)', application: 'Ruggedized AV network Ethernet', ipRating: 'IP65', standard: 'IEEE 802.3' },
        { name: 'OpticalCON DUO (LC)', application: 'Live event fibre video transport', ipRating: 'IP65', standard: 'SMPTE 304M' },
        { name: 'powerCON TRUE1 (Neutrik)', application: 'Stage power distribution (16A/20A)', ipRating: 'IP65', standard: 'IEC 60309' },
      ],
      cables_detail: [
        '75Ω RG-6 or Belden 1694A SDI cable',
        'AES/EBU 110Ω twisted pair (digital audio)',
        'Socapex breakout multi-cable (19 way)',
        '2.5mm² flexible stage power cable',
        'Fibre BNC hybrid broadcast cable',
      ],
      standards: ['SMPTE ST 2082 (12G-SDI)', 'AES3 110Ω', 'IEC 61076', 'EIA 422', 'ANSI E1.11 (DMX)'],
      useCases: [
        'OB van production truck SDI routing',
        'Stadium concert lighting rig power',
        'Concert hall audio snake cabling',
        'LED wall videowall signal distribution',
        'ESports arena broadcast fiber plant',
      ],
    },

  ],

};

/* ── Flatten for search ── */
const ALL_INDUSTRIES = Object.values(INDUSTRIES).flat();

/* ── Color palettes for cards ── */
const ACCENT_COLORS = {
  'Factory Automation & Robotics': '#f97316',
  'Heavy Industry & Mining': '#78716c',
  'Food & Beverage Processing': '#84cc16',
  'Pharmaceuticals & Chemical Processing': '#06b6d4',
  'Logistics, Warehousing & Packaging': '#f59e0b',
  'Machine Building & OEMs': '#94a3b8',
  'Semiconductor Manufacturing': '#818cf8',
  'Automotive Manufacturing': '#3b82f6',
  'Commercial Vehicles & Trucking': '#f59e0b',
  'Railway & Mass Transit': '#e11d48',
  'Aerospace, Aviation & Defense': '#64748b',
  'Marine & Maritime': '#0ea5e9',
  'Oil & Gas (Upstream/Downstream)': '#854d0e',
  'Power Generation & Utilities': '#fbbf24',
  'Renewable Energy (Solar & Wind)': '#22c55e',
  'Water & Wastewater Management': '#0ea5e9',
  'Telecom & Broadband Networks': '#a855f7',
  'Data Centers & Cloud Computing': '#6366f1',
  'Consumer Electronics & AV': '#ec4899',
  'Machine Vision & Imaging': '#14b8a6',
  'Medical Imaging & Diagnostics': '#ec4899',
  'Patient Monitoring & Nursing': '#f43f5e',
  'Test & Measurement': '#f97316',
  'Building Automation & HVAC': '#14b8a6',
  'Intelligent Traffic Systems': '#16a34a',
  'Agriculture & Smart Farming': '#65a30d',
  'Broadcasting & Entertainment': '#d946ef',
};
