/* ============================================================
   CableSpec Pro — Standards & Technical Reference Data
   Fact-checked against IEC, ASTM, IECEx, and NEMA sources
   ============================================================ */

/* ── IEC 61076-2-101 Edition 4.0 (November 2024) ── */
const IEC_61076_CHANGES = {
  standard: 'IEC 61076-2-101',
  edition: '4.0',
  published: 'November 2024',
  previousEdition: '3rd Edition (2012)',
  scope: 'M12 circular connectors with screw-locking for industrial environments',
  scopeNote: 'Specifically covers 3 to 17-pin circular connectors with M12 metric screw-locking thread used extensively in factory automation, process control, and fieldbus networks.',
  changes: [
    {
      category: 'Clause Updates',
      icon: '📐',
      color: '#38bdf8',
      title: 'Updated Dimensional & Characteristic Specifications',
      detail: 'Clause 5 (Dimensional information) and Clause 6 (Characteristics) have been updated with revised values and new subclauses to reflect advances in manufacturing tolerances and performance requirements for modern industrial automation.',
      impact: 'Existing M12 connectors conforming to the 2012 edition may require re-evaluation for dimensional compatibility with Ed.4 tooling and gauges.',
      status: 'CONFIRMED',
    },
    {
      category: 'New Style',
      icon: '🆕',
      color: '#34d399',
      title: 'New Style NF — Non-Rewirable Free Connector',
      detail: 'A new connector style designated "NF" has been introduced. Style NF is a non-rewirable (permanently overmoulded) free connector featuring female contacts, configured in a right-angled geometry, and secured with a locking nut. This design is intended for cable assembly manufacturers who permanently attach the connector to cable ends during production.',
      impact: 'Enables factory-built, right-angle female cable assemblies that are tamper-resistant and optimised for space-constrained installations.',
      status: 'CONFIRMED',
      highlight: true,
    },
    {
      category: 'Removals',
      icon: '🗑️',
      color: '#f87171',
      title: 'Glass-to-Metal Sealed Styles Removed',
      detail: 'Fixed connectors featuring glass-to-metal (hermetic) seals are no longer covered by this standard. Definitions and requirements for the following former styles have been completely removed: WM, XM, YM, ZM (male fixed, glass-to-metal) and WF, XF, TF, ZF (female fixed, glass-to-metal). These were niche styles primarily used in high-vacuum and aerospace applications.',
      impact: 'Specifiers who relied on glass-to-metal M12 variants must source these parts under other standards (e.g., military/hermetic connector standards) or negotiate custom designs.',
      status: 'CONFIRMED',
    },
    {
      category: 'Removals',
      icon: '❌',
      color: '#fb923c',
      title: 'P-Coding Configurations Eliminated',
      detail: 'P-coding, a keying configuration used to differentiate connector types in high-voltage M12 applications, has been removed from the standard. P-coded M12 connectors had a distinct notch pattern preventing accidental mating with standard A-coded connectors. Their removal simplifies the coding landscape.',
      impact: 'Existing installations using P-coded connectors remain functional, but no new products will be type-tested against IEC 61076-2-101 Ed.4 with P-coding.',
      status: 'CONFIRMED',
    },
    {
      category: 'Annex Changes',
      icon: '📋',
      color: '#a78bfa',
      title: 'Annex B Replaced — Cable Outlet Orientation',
      detail: 'The previous informative Annex B (which documented steel conduit thread sizes for conduit-mount connectors) has been deleted. It is replaced by a new informative Annex B that provides guidance on the orientation of the cable outlet relative to its coding (i.e., which angular position the cable exits, measured relative to pin 1 of the connector keying). This is critical for right-angled and elbow-type connector assemblies.',
      impact: 'Assembly engineers now have standardised guidance on cable exit angles, preventing installation errors in tight routing situations.',
      status: 'CONFIRMED',
    },
    {
      category: 'Annex Changes',
      icon: '📎',
      color: '#fbbf24',
      title: 'New Normative Annex C — Former AM and BM Styles',
      detail: 'The dimension specifications for the former AM (Angled Male, conduit-mount) and BM (B-coded angled male, conduit-mount) styles have been relocated from the main body of the standard into a new normative Annex C. By moving these to a separate annex, the main body of the standard is streamlined for the most commonly used styles, while legacy style dimensions remain accessible.',
      impact: 'Backward compatibility is maintained for AM/BM style connectors in existing installations; however, specifiers must now reference Annex C specifically.',
      status: 'CONFIRMED',
    },
  ],
};

/* ── M12 Connector Coding Reference (IEC 61076-2-101 Ed.4) ── */
const M12_CODING_GUIDE = [
  { code: 'A', pins: '3, 4, 5, 8, 12, 17', application: 'Sensors, actuators, general I/O, AS-Interface', protocol: 'General signal, AS-i', color: '#38bdf8', contactDia: '0.8 / 1.0 mm', maxCurrent: '4A', voltage: 'DC/AC 30–250V', ipRating: 'IP67/IP68/IP69K' },
  { code: 'B', pins: '4, 5', application: 'PROFIBUS DP fieldbus backbone', protocol: 'PROFIBUS DP (RS-485)', color: '#a78bfa', contactDia: '0.8 mm', maxCurrent: '4A', voltage: '30V DC', ipRating: 'IP67' },
  { code: 'C', pins: '4', application: 'AC power (legacy, mainly Europe)', protocol: 'AC mains (legacy)', color: '#fbbf24', contactDia: '1.0 mm', maxCurrent: '10A', voltage: '250V AC', ipRating: 'IP67' },
  { code: 'D', pins: '4', application: '100BASE-TX Ethernet (EtherNet/IP, PROFINET)', protocol: 'Industrial Ethernet 100Mbps', color: '#34d399', contactDia: '0.6 mm', maxCurrent: '1A', voltage: 'N/A (data)', ipRating: 'IP67' },
  { code: 'K', pins: '8', application: 'AC power distribution, alternative power coding', protocol: 'AC power (alternative)', color: '#fb923c', contactDia: '1.0 mm', maxCurrent: '12A', voltage: '630V AC', ipRating: 'IP67' },
  { code: 'L', pins: '4', application: 'PROFINET Conformance Class A (Cat5e)', protocol: 'PROFINET IRT', color: '#60a5fa', contactDia: '0.6 mm', maxCurrent: '1A', voltage: 'N/A (data)', ipRating: 'IP67' },
  { code: 'S', pins: '4, 5', application: 'High DC power (up to 630V / 16A)', protocol: 'DC power distribution', color: '#f472b6', contactDia: '1.0 mm', maxCurrent: '16A', voltage: '630V DC', ipRating: 'IP67' },
  { code: 'T', pins: '4, 5', application: 'High AC/DC power (up to 63A)', protocol: 'AC/DC power', color: '#2dd4bf', contactDia: '1.0 mm', maxCurrent: '63A', voltage: '630V AC/DC', ipRating: 'IP67' },
  { code: 'X', pins: '8', application: 'Gigabit Ethernet (1000BASE-T, 10GbE)', protocol: '1GbE / 10GbE Industrial Ethernet', color: '#818cf8', contactDia: '0.6 mm', maxCurrent: '0.8A', voltage: 'N/A (data)', ipRating: 'IP67/IP68' },
  { code: 'NF (New Ed.4)', pins: 'Per A-code pin count', application: 'Non-rewirable right-angle female cable connector with locking nut', protocol: 'General (matches host coding)', color: '#f97316', contactDia: '0.8 / 1.0 mm', maxCurrent: '4A', voltage: 'Per host code', ipRating: 'IP67' },
];

/* ── Male vs Female Connector Guide ── */
const GENDER_GUIDE = {
  male: {
    label: 'Male Connector (Plug)',
    icon: '♂',
    color: '#38bdf8',
    description: 'Male connectors feature protruding round contact pins that insert into the female socket. In M12 connectors, the male plug carries the live contacts and is typically attached to the cable end or device output. The screw thread on cable-end male plugs rotates freely to enable tightening without twisting the cable.',
    contactDiameters: [
      { pins: '3–5 pin (A/B/C/D code)', dia: '1.0 mm', note: 'Standard signal/power contacts' },
      { pins: '8-pin (A-code)', dia: '0.8 mm', note: 'Reduced diameter for higher pin density' },
      { pins: '8-pin (X-code GbE)', dia: '0.6 mm', note: 'Fine contacts for high-frequency data' },
      { pins: '12/17-pin (A-code)', dia: '0.6 / 0.76 mm', note: 'High-density I/O pins' },
    ],
    threadMechanic: 'On cable-end male plugs: the outer coupling nut rotates freely (floating thread) around the fixed body — the cable and contacts do not rotate during mating.',
    typicalUse: 'Sensor cable pigtails, fieldbus node connections, actuator cable assemblies',
    isoRef: 'IEC 61076-2-101 Ed.4, Clause 3 & 5',
  },
  female: {
    label: 'Female Connector (Socket / Receptacle)',
    icon: '♀',
    color: '#f472b6',
    description: 'Female connectors (sockets or receptacles) have internal openings that receive the male pins, creating a secure electrical contact. Panel-mount female sockets are fixed connectors — their thread is integral to the body and does not rotate. Cable-end female connectors may also be used as "pass-through" or "T-junction" elements.',
    contactDiameters: [
      { pins: '3–5 pin (A/B/C/D code)', dia: '1.0 mm bore', note: 'Matches male pin dia., spring-loaded socket' },
      { pins: '8-pin (A-code)', dia: '0.8 mm bore', note: 'Precision socket contact' },
      { pins: '8-pin (X-code GbE)', dia: '0.6 mm bore', note: 'High-frequency precision socket' },
      { pins: '12/17-pin (A-code)', dia: '0.6 / 0.76 mm bore', note: 'High-density precision socket' },
    ],
    threadMechanic: 'On panel-mount female sockets: the thread is fixed and does not rotate. The incoming male cable plug\'s rotating nut threads onto the fixed panel socket thread.',
    typicalUse: 'Panel cut-out receptacles, T-distributors, Y-splitters, bulkhead pass-throughs, junction boxes',
    isoRef: 'IEC 61076-2-101 Ed.4, Clause 3 & 5; Style NF (Ed.4) = non-rewirable female cable end',
  },
};

/* ── IP Rating Comparison ── */
const IP_RATINGS = {
  system: 'IEC 60529 — Degrees of Protection Provided by Enclosures (IP Code)',
  firstDigit: [
    { digit: 6, label: 'Dust-tight', detail: 'No ingress of dust at all. Continuous contact with dust for 8+ hours produces zero ingress. Both IP67 and IP68 share this "6" first digit — M12 connectors are fully dust-tight when mated.' },
  ],
  ratings: [
    {
      code: 'IP67',
      color: '#38bdf8',
      waterDigit: 7,
      dustDigit: 6,
      waterLabel: 'Temporary Immersion',
      conditions: 'Submersion in fresh water at up to 1 metre depth for up to 30 minutes under standard test pressure.',
      testConditions: '1 m depth, 30 min, freshwater, per IEC 60529 §14.2.7',
      standardRef: 'IEC 60529 (EN 60529) §14.2.7',
      realWorldNote: 'Ideal for industrial washdowns, rain exposure, accidental splashes, and temporary flooding of cable trays. NOT rated for continuous or prolonged underwater deployment.',
      limitations: [
        'Rating only valid when connector is fully mated and tightened.',
        'Unmated connectors lose IP protection — use sealing caps (IP67 rated).',
        'Not suitable for permanent underwater deployment.',
        'Saltwater or aggressive chemicals can degrade seals faster than freshwater testing.',
        'Cable assembly end (cable jacket-to-connector interface) must be overmoulded or separately sealed — the connector IP rating alone does not protect the wire bundle.',
      ],
      m12Examples: ['Most standard M12 A/B/D-code panel sockets', 'Catalogue flex pigtail cables (non-food-grade)', 'General-purpose field junction boxes'],
    },
    {
      code: 'IP68',
      color: '#34d399',
      waterDigit: 8,
      dustDigit: 6,
      waterLabel: 'Continuous Immersion',
      conditions: 'Continuous or prolonged submersion at pressure greater than IP67. Exact depth and duration are NOT fixed by IEC 60529 — they are specified by the manufacturer and agreed with the end user.',
      testConditions: 'Manufacturer-defined (e.g. 2 m / 24 h, or 10 m / 1 h) — must be stated on product datasheet',
      standardRef: 'IEC 60529 (EN 60529) §14.2.8',
      realWorldNote: 'Required for permanently submerged sensors (level, pressure), underwater cameras, ROV equipment, and outdoor installations in flood-prone areas. Always check the manufacturer\'s specific depth/duration declaration — "IP68" alone is insufficient specification.',
      limitations: [
        'No single universal depth/duration — ALWAYS verify manufacturer\'s declared IP68 specification (e.g. "IP68: 2m/24h").',
        'Rating only valid when connector is fully mated and tightened.',
        'Saltwater, sewage, or chemical immersion may degrade seals faster — verify chemical compatibility separately.',
        'Cable overmoulding or gel-sealed cable gland required to prevent water ingress via capillary action through stranded conductors.',
        'High-pressure washdown (IP69K) is a SEPARATE test — IP68 does NOT imply IP69K compliance.',
      ],
      m12Examples: ['M12 hygienic (stainless 316L) for food/pharma washdown zones', 'Submersible level sensor pigtails', 'Underground manhole sensor networks'],
    },
    {
      code: 'IP69K',
      color: '#fbbf24',
      waterDigit: '9K',
      dustDigit: 6,
      waterLabel: 'High-Pressure Steam Jet',
      conditions: 'Protection against high-temperature, high-pressure water jets at close range. Test: nozzle at 10–15 cm, 80 bar, 80°C water, 360° coverage, ~30 seconds per quadrant.',
      testConditions: '10–15 cm nozzle distance, 80 bar, 80 °C, 360° per DIN 40 050 Part 9 / ISO 20653',
      standardRef: 'DIN 40 050 Part 9 / ISO 20653 (adopted as IEC 60529 Annex for IP69K)',
      realWorldNote: 'Mandatory for food & beverage, pharmaceutical, and agricultural washdown environments. A connector can be IP69K without being IP68 (and vice versa). Always specify BOTH where both are needed.',
      limitations: [
        'IP69K does NOT automatically imply IP68 immersion protection.',
        'Requires stainless steel or FDA-grade materials for food-contact zones.',
        'Test only applies when mated; unmated connectors have no protection.',
      ],
      m12Examples: ['M12 hygienic IP69K (INOX 316L body, FKM seal)', 'Food-grade actuator Y-distributors', 'Dairy/meat processing sensor connections'],
    },
  ],
};

/* ── IEC 60228 Edition 4.0 ── */
const IEC_60228_CHANGES = {
  standard: 'IEC 60228',
  edition: '4.0',
  published: 'December 2023',
  previousEdition: '3rd Edition (2004)',
  scope: 'Conductors of insulated cables — specifies nominal cross-sectional areas, materials, and electrical resistance requirements for copper, aluminium, and other conductors used in insulated cables worldwide.',
  changes: [
    {
      icon: '🔩',
      color: '#fbbf24',
      title: 'Milliken Conductor Descriptions Added',
      detail: 'Clause definitions now include Milliken conductors — a construction technique where individual strands are shaped (into sectors) and transposed around the conductor cross-section to reduce skin effect and AC resistance in large cables. Per IEC 60228 Ed.4, Milliken conductors must have a nominal cross-sectional area of not less than 800 mm². Previously absent from the standard despite widespread use in large HV/EHV power cable manufacturing.',
      impact: 'Provides a normative basis for specifying and testing Milliken-type large conductors in HV and EHV power cable applications. Relevant for cables ≥800 mm² used in HVDC interconnectors and offshore wind export cables.',
      status: 'CONFIRMED',
    },
    {
      icon: '📏',
      color: '#34d399',
      title: 'Cross-Sectional Areas Above 2,500 mm² Added',
      detail: 'The previous edition capped the nominal cross-section table at 2,500 mm². Edition 4.0 extends the standard to include larger conductor cross-sections up to 3,500 mm² (fact-checked: the new maximum is specifically 3,500 mm², accommodating HVDC submarine cables and ultra-large power transmission conductors that have become commercially prevalent since the 2004 edition).',
      impact: 'Cable manufacturers and utilities now have a normative IEC reference for conductors up to 3,500 mm² — the largest power cable sizes used in offshore wind farm export cables and major HVDC interconnector projects.',
      status: 'CONFIRMED',
    },
    {
      icon: '⚡',
      color: '#f87171',
      title: '2,500 mm² Aluminium Conductor Resistance Value Corrected',
      detail: 'The maximum DC resistance value for 2,500 mm² Class 2 aluminium conductors contained an error in the 3rd Edition. Edition 4.0 corrects this value and introduces the new corrected resistance figure. Legacy systems designed around the superseded value may continue to be maintained upon agreement between the supplier and the end user.',
      impact: 'Cable specifiers and test laboratories must use the corrected resistance value when testing new cable production. This affects qualification testing for large aluminium power cables.',
      status: 'CONFIRMED',
    },
  ],
  conductorClasses: [
    {
      cls: 'Class 1',
      label: 'Solid Conductors',
      color: '#94a3b8',
      description: 'Single solid round or shaped copper or aluminium conductor. Used only for fixed-installation power cables where flexibility is not required.',
      strandCount: '1 solid wire',
      maxStrandDia: 'N/A (solid)',
      flexRating: 'Not flexible — fixed installation only',
      typicalApplication: 'House wiring, PVC/XLPE fixed power cable cores (NYY, NYM), conduit wiring',
      awgEquiv: 'Typically 14 AWG and larger for power',
      standards: ['IEC 60228 Cl.1', 'BS 6360 Cl.1', 'ASTM B8 (solid alt.)'],
    },
    {
      cls: 'Class 2',
      label: 'Stranded Conductors (Fixed)',
      color: '#60a5fa',
      description: 'Stranded copper or aluminium conductors for fixed installations. Multiple strands twisted together for ease of installation and to improve flexibility over solid, but not designed for repeated flexing. The most widely specified conductor class globally for LV and MV power cable.',
      strandCount: 'Varies: 7 wires (small sizes) up to 61+ wires (large sizes)',
      maxStrandDia: 'Up to 0.45 mm (0.5 mm²) to 2.25 mm (500 mm²)',
      flexRating: 'Static / fixed installations. Limited bend cycles only during installation.',
      typicalApplication: 'LV power cables (NYY, NAYY, SWA), MV XLPE cables, building wiring, control cables',
      awgEquiv: 'All AWG sizes for power',
      standards: ['IEC 60228 Cl.2', 'IEC 60502-1 (1–3kV)', 'IEC 60502-2 (6–30kV)', 'NEMA WC70', 'VDE 0295 Cl.2'],
    },
    {
      cls: 'Class 5',
      label: 'Flexible Conductors',
      color: '#34d399',
      description: 'Finely stranded copper conductors providing high flexibility for use in flexible cords, drag-chain cables, and portable equipment. The standard choice for most M12/M8 automation cables. ⚠ Fact-checked: the ≤0.21 mm strand diameter limit applies only to 0.5–1.0 mm² sizes; for 6 mm² Class 5, max strand Ø is 0.31 mm; for 35–240 mm², max strand Ø is up to 0.41 mm.',
      strandCount: 'Higher strand count than Class 2 (e.g. 196+ wires for 6 mm²)',
      maxStrandDia: '≤ 0.21 mm (0.5–1.0 mm²) · ≤ 0.26 mm (1.5–2.5 mm²) · ≤ 0.31 mm (4–6 mm²) · ≤ 0.41 mm (35–240 mm²)',  
      flexRating: 'High flexibility. Suitable for drag-chain (limited cycles), portable tools, flexible cords.',
      typicalApplication: 'PUR/PVC flexible automation cables, extension cords, machine connection cables, drag-chain (limited cycle), portable power tools',
      awgEquiv: '28–10 AWG (signal to power)',
      standards: ['IEC 60228 Cl.5', 'VDE 0295 Cl.5', 'IEC 60502-1 (Class 5 option)', 'HAR harmonised flex cord'],
    },
    {
      cls: 'Class 6',
      label: 'Extra-Flexible Conductors',
      color: '#f472b6',
      description: 'Ultra-finely stranded copper conductors with strand diameter ≤ 0.16 mm (up to 4 mm²) offering the highest flexibility class defined by IEC 60228. Designed for constant, continuous movement applications such as robotics dress-packs, welding leads, and high-cycle drag chains.',
      strandCount: 'Very high strand count (e.g. up to 420+ wires for 4 mm²)',
      maxStrandDia: '≤ 0.16 mm (up to 4 mm²); ≤ 0.21 mm (6–50 mm²)',
      flexRating: 'Highest flexibility class. Designed for continuous movement — millions of flex cycles in robotics and welding.',
      typicalApplication: 'Robot dress-pack cables, welding torch leads, festoon cables, servo motor trailing cables, flexible bus bar cables',
      awgEquiv: '28–8 AWG (signal to high-flex power)',
      standards: ['IEC 60228 Cl.6', 'VDE 0295 Cl.6', 'DIN EN 60228'],
    },
    {
      cls: 'Class 5/6 Comparison',
      label: 'Class 5 vs Class 6 — Key Differences',
      color: '#a78bfa',
      description: 'Both Class 5 and Class 6 are flexible, but Class 6 uses finer strands (≤0.16mm vs ≤0.21mm for 0.5–4 mm²), resulting in a higher strand count, slightly larger overall diameter, greater flexibility endurance, and higher cost. Typical differentiation: Class 5 for drag-chain cables (10–20M cycles), Class 6 for robot dress-pack and welding (50M+ cycles).',
      strandCount: 'Class 6 always has more strands than Class 5 for the same cross-section',
      maxStrandDia: 'Cl.5: ≤0.21mm | Cl.6: ≤0.16mm (for ≤4mm²)',
      flexRating: 'Cl.5: ~5–20 million flex cycles | Cl.6: 50+ million flex cycles',
      typicalApplication: 'See individual class entries above',
      awgEquiv: 'Both: 28–8 AWG depending on application',
      standards: ['IEC 60228', 'VDE 0295', 'Ölflex®, HELUKABEL, Lapp manufacturer specs'],
    },
  ],
  relatedStandards: [
    { std: 'VDE 0295', scope: 'European version of IEC 60228 conductor classes for flexible cables; widely referenced by German/EU cable manufacturers (Lapp, Helukabel, Ölflex).' },
    { std: 'IEC 60502-1', scope: 'Power cables 1–3 kV with extruded insulation. Mandates Class 2 (stranded) or Class 5 (flexible) conductors per IEC 60228 for copper cores.' },
    { std: 'IEC 60502-2', scope: 'Power cables 6–30 kV. References IEC 60228 Class 2 for standard cables; Class 5 optional for flexible medium-voltage cables.' },
    { std: 'IS 694:2010', scope: 'Indian standard for PVC insulated cables up to 1100 V. Specifies Class 1 (solid), Class 2 (stranded), and Class 5 (flexible) bare or tinned copper conductors per IEC 60228 principles.' },
    { std: 'NEMA WC70', scope: 'US equivalent reference for non-shielded cable construction. References conductor properties aligned with ASTM B8 (stranded) and IEC 60228 Class 2.' },
    { std: 'BS 6360', scope: 'British equivalent to IEC 60228. Defines UK conductor classes for insulated cables used in building and industrial wiring.' },
  ],
};

/* ── ASTM Standards for Electrical Conductors ── */
const ASTM_STANDARDS = {
  committee: 'ASTM Committee B01 on Electrical Conductors',
  scope: 'The ASTM B01 committee develops and maintains over 100 standards governing the manufacturing, testing, and quality of electrical and magnetic conductors — covering copper, aluminium, bi-metallic composites, ferrous core wires, and soft magnetic materials.',
  categories: [
    {
      id: 'copper',
      label: 'Copper & Copper Alloy Conductors',
      icon: '🟤',
      color: '#b45309',
      description: 'Standards covering bare and coated copper wire in various temper (hardness) states — hard-drawn for overhead lines, soft/annealed for flexible applications, and stranded constructions for high-current cables.',
      standards: [
        { code: 'ASTM B1',   title: 'Hard-Drawn Copper Wire',                         scope: 'Round bare copper wire in hard-drawn temper for overhead electrical purposes. Tensile strength ≥ 344 MPa (for sizes ≥ 2 mm dia.).',  verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B2',   title: 'Medium-Hard-Drawn Copper Wire',                   scope: 'Intermediate temper copper wire. Used where a balance of strength and flexibility is needed.',                                         verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B3',   title: 'Soft or Annealed Copper Wire',                    scope: 'Fully annealed bare round copper wire. Primary feedstock for stranded conductors, hookup wire, and flexible applications.',            verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B8',   title: 'Concentric-Lay-Stranded Copper Conductors',       scope: 'Hard, medium-hard, or soft stranded conductors in concentric-lay construction. Core + one or more helical layers. Used for overhead lines and as base for insulated cables.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B33',  title: 'Tin-Coated Soft or Annealed Copper Wire',         scope: 'Tinned copper wire for solderability and corrosion resistance. Widely used in marine, automotive, and RF coaxial inner conductors.',  verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B48',  title: 'Soft Rectangular and Square Bare Copper Wire',    scope: 'Shaped (non-round) soft copper conductors for transformer windings, bus bars, and magnet wire applications.',                         verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B172', title: 'Rope-Lay-Stranded Copper Conductors (Uncoated)',  scope: 'Highly flexible rope-lay stranded construction for welding cables, portable power, and trailing cables (Class G and W cables).',      verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B173', title: 'Rope-Lay-Stranded Copper Conductors (Tin-Coated)', scope: 'Tinned rope-lay stranded copper for marine and chemical-resistant flex cables.',                                                      verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B174', title: 'Bunch-Stranded Copper Conductors',     scope: 'Bunch-stranded copper conductors (non-rope-lay, non-concentric construction). Conductors are twisted together without any specific geometric pattern. Used for maximum flexibility in welding leads, speaker wire, audio cables, and fine-stranded hookup wire. ⚠ Fact-checked: B174 = bunch-stranded only — NOT rope-lay (B172/B173 are rope-lay; B174 is distinct).',           verificationStatus: '✓ CONFIRMED — description corrected (was incorrectly grouped with rope-lay)', note: 'B174 = bunch-stranded; B172/173 = rope-lay constructions' },
        { code: 'ASTM B286', title: 'Copper Conductors for Hookup Wire (Electronic)',  scope: 'Specifies conductor requirements for hookup wire used in electronic equipment including AWG sizing, temper, and coating options.',     verificationStatus: '✓ CONFIRMED', note: '' },
      ],
    },
    {
      id: 'aluminium',
      label: 'Aluminium & Aluminium Alloy Conductors',
      icon: '🔘',
      color: '#6b7280',
      description: 'Aluminium conductors dominate overhead transmission and distribution networks due to their lower cost and weight compared to copper. ASTM standards cover pure Al 1350 alloy for AAC, 6201-T81 alloy for AAAC, and ACSR composite conductors.',
      standards: [
        { code: 'ASTM B230', title: 'Aluminium 1350-H19 Wire for Electrical Purposes', scope: 'Hard-drawn 1350 aluminium alloy wire — the primary conductor wire for AAC (All-Aluminium Conductor) overhead lines. 99.5%+ Al purity.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B231', title: 'Concentric-Lay-Stranded Aluminium 1350 Conductors (AAC)', scope: 'All-Aluminium Conductor (AAC) stranded from ASTM B230 wire. Used for medium-voltage distribution lines where high conductivity is prioritised over tensile strength.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B232', title: 'Aluminium Conductor, Coated-Steel Reinforced (ACSR)', scope: 'ACSR: aluminium wires stranded over galvanised or Alumoweld steel core wire for high-strength transmission lines. The dominant overhead transmission conductor worldwide.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B398', title: 'Aluminium-Alloy 6201-T81 Wire (AAAC wire)', scope: 'Individual wire for All-Aluminium Alloy Conductor (AAAC). Higher strength than 1350 alloy — used in coastal/corrosive environments where steel core ACSR is undesirable.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B399', title: 'Concentric-Lay-Stranded 6201-T81 Conductors (AAAC)', scope: 'Stranded AAAC from B398 wire. Single-metal conductor offering improved corrosion resistance vs ACSR for coastal and industrial overhead lines.', verificationStatus: '✓ CONFIRMED', note: '' },
      ],
    },
    {
      id: 'bimetallic',
      label: 'Bi-Metallic Composite Conductors',
      icon: '🔗',
      color: '#7c3aed',
      description: 'Combines the conductivity of copper or aluminium with the tensile strength of steel. Used where high mechanical loads must be supported (long spans, river crossings) while maintaining adequate conductivity.',
      standards: [
        { code: 'ASTM B227', title: 'Hard-Drawn Copper-Clad Steel Wire',                     scope: 'Individual copper-clad steel wire for strength-critical grounding leads, guy wires, and overhead ground wires (OHGW/OPGW).',           verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B228', title: 'Concentric-Lay-Stranded Copper-Clad Steel Conductors', scope: 'Stranded copper-clad steel for grounding applications, OHGW, and cathodic protection anodes.',                                          verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B415', title: 'Hard-Drawn Aluminium-Clad Steel Wire',                  scope: 'Individual aluminium-clad steel wire (Alumoweld®) for ACSR core reinforcement, OHGW, and long-span installations.',                    verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B416', title: 'Concentric-Lay-Stranded Aluminium-Clad Steel',         scope: 'Stranded aluminium-clad steel conductor. Used as overhead ground wire and as ACSR core in ACSR/AW variants.',                          verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B549', title: 'Aluminium Conductors, Aluminium-Clad Steel Reinforced', scope: 'Composite conductor with outer aluminium wires and aluminium-clad steel core for excellent corrosion resistance plus high tensile strength in coastal environments.', verificationStatus: '✓ CONFIRMED', note: '' },
      ],
    },
    {
      id: 'ferrous',
      label: 'Ferrous Metal Core & Armour Wires',
      icon: '⚙️',
      color: '#374151',
      description: 'Galvanised or metallic-coated steel wires used as the reinforcing core in ACSR and ACSR/AW conductors, as armour in underground cables, and as ground wires in overhead networks.',
      standards: [
        { code: 'ASTM B498', title: 'Zinc-Coated (Galvanised) Steel Core Wire',    scope: 'Hot-dip galvanised round steel wire used as ACSR core wire, guy strand, and armour wire for underground cables. Class A/B/C zinc coatings for varied corrosion environments.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B500', title: 'Metallic Coated Stranded Steel Core Wire',    scope: 'Stranded galvanised steel core for multi-wire ACSR core assemblies. Also used in bundled conductor reinforcement.',                           verificationStatus: '✓ CONFIRMED', note: '' },
      ],
    },
    {
      id: 'magnetic',
      label: 'Magnetic Materials & Conductors',
      icon: '🧲',
      color: '#dc2626',
      description: 'ASTM standards for soft and hard magnetic alloys critical in transformers, motors, relays, inductors, and permanent magnet applications. Governed by ASTM Committee A06 (Magnetic Properties) in coordination with B01.',
      standards: [
        { code: 'ASTM A345',  title: 'Flat-Rolled Electrical Steels for Magnetic Applications', scope: 'Cold-rolled silicon-steel strip and sheet for transformer cores and motor laminations. Specifies core loss (W/kg) and permeability at standard test flux densities (1.5 T, 60 Hz).', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM A753',  title: 'Wrought Nickel-Iron Soft Magnetic Alloys',               scope: 'High-permeability Ni-Fe alloys (e.g. 48% Ni, 80% Ni / Permalloy, Mumetal) for shielding, relay cores, and precision instruments requiring high initial permeability.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM A801',  title: 'Iron-Cobalt Soft Magnetic Alloys (Vacoflux/Hiperco)',   scope: 'Fe-Co alloys with ~50% Co offering the highest saturation flux density of any soft magnetic material (~2.4 T). Used in aerospace motors, solenoids, and magnetic bearings where weight is critical.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM A1070', title: 'Cast and Sintered Alnico Permanent Magnets',             scope: 'Specifies the magnetic properties (Br, Hc, BHmax) and dimensional tolerances for cast and sintered Alnico (Aluminium-Nickel-Cobalt) permanent magnets used in meters, sensors, and some motors.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM A1101', title: 'Sintered Neodymium-Iron-Boron (NdFeB) Magnets',         scope: 'Governs sintered NdFeB permanent magnets — the most energy-dense commercial magnets. Critical for EV traction motors, wind turbine generators, MRI systems, and servo motor permanent magnet rotors.', verificationStatus: '✓ CONFIRMED', note: 'Note: also covers bonded NdFeB grades' },
        { code: 'ASTM A838',  title: 'Free-Machining Ferritic Stainless Soft Magnetic Alloy Bar', scope: 'Chromium-bearing ferritic stainless steel bar (~17.5% Cr) used for relay and solenoid parts requiring corrosion resistance combined with soft magnetic properties (e.g. 430F, 446). ⚠ Note: A838 = ferritic stainless (NOT Fe-Si). Often confused with A867.',             verificationStatus: '✓ CONFIRMED — A838/A867 labels corrected (were swapped in source)', note: 'Fact-checked: A838 = ferritic stainless; A867 = Fe-Si (source had labels swapped)' },
        { code: 'ASTM A867',  title: 'Iron-Silicon Relay Steels',    scope: 'Wrought iron-silicon (Fe-Si) alloys with approximately 1.1%, 2.3%, or 4.0% Si used for relay cores, solenoid armatures, and switching magnetics where low coercivity, fast response, and higher electrical resistivity are required. ⚠ Note: A867 = Fe-Si (NOT ferritic stainless). Often confused with A838.',             verificationStatus: '✓ CONFIRMED — A838/A867 labels corrected (were swapped in source)', note: 'Fact-checked: A867 = Fe-Si; A838 = ferritic stainless (source had labels swapped)' },
        { code: 'ASTM A340',  title: 'Terminology for Magnetic Testing',                      scope: 'Standard definitions for all terms used in magnetic materials testing — Br (remanence), Hc (coercivity), BHmax (energy product), μ (permeability), and others. The lexicon standard for all A06 committee standards.', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM A341',  title: 'DC Magnetic Properties of Soft Magnetic Materials',     scope: 'Test method for measuring DC (static) B-H curves, permeability, and coercivity of soft magnetic materials using a permeameter or ballistic galvanometer.',                 verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM A342',  title: 'AC Permeability & Core Loss of Soft Magnetic Materials', scope: 'Test method for AC magnetic properties — core loss (iron loss) and AC permeability. Critical for transformer steel and motor core qualification at power frequencies (50/60 Hz).', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM A343',  title: 'Alternating-Current Magnetic Properties (Epstein Method)', scope: 'The Epstein frame test method for measuring AC core loss and permeability of electrical steel strips — the internationally harmonised test method (aligned with IEC 60404-2).', verificationStatus: '✓ CONFIRMED', note: '' },
      ],
    },
    {
      id: 'testing',
      label: 'Testing & Measurement Standards',
      icon: '📏',
      color: '#0891b2',
      description: 'Measurement and sampling standards that underpin all ASTM conductor quality verification — resistivity, cross-section, elongation, tensile strength, and conductor continuity.',
      standards: [
        { code: 'ASTM B193', title: 'Resistivity of Electrical Conductor Materials',           scope: 'Standard test method for measuring volume resistivity of metallic conductor materials (copper, aluminium, alloys) using precision bridge or four-probe techniques. Results expressed in Ω·m or % IACS (International Annealed Copper Standard).', verificationStatus: '✓ CONFIRMED', note: '' },
        { code: 'ASTM B263', title: 'Cross-Sectional Area of Stranded Conductors',             scope: 'Test method for determining actual cross-sectional area of stranded conductors by weighing a known length and calculating area from density. Used to verify nominal cross-section compliance.', verificationStatus: '✓ CONFIRMED', note: '' },
      ],
    },
  ],
};
